using System.Text.Json.Nodes;
using DrawOffer.Core.Models;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI;
namespace DrawOffer.App.Views;

public sealed class CareerApplicationDetailPage : Page {
    private readonly CareerApplication _seed;
    private CareerApplication _item;
    private readonly Action _back;
    private readonly Action<string,CareerApplication> _perform;
    private readonly CancellationTokenSource _life=new();
    private readonly StackPanel _page=new(){Spacing=24,Padding=new Thickness(32,35,32,32),MaxWidth=924,HorizontalAlignment=HorizontalAlignment.Stretch};
    private List<JsonNode> _sessions=[];
    private bool _loading=true;
    private string? _error;
    private static readonly FontFamily Sans=new("ms-appx:///Assets/Library/LibrarySans-Regular.otf#DrawOffer Library Sans"),Serif=new("ms-appx:///Assets/Library/LibrarySerif-SemiBold.ttf#DrawOffer Library Serif");
    private static SolidColorBrush Brush(uint value)=>new(ColorHelper.FromArgb(255,(byte)(value>>16),(byte)(value>>8),(byte)value));
    private static TextBlock Text(string text,double size=13,uint color=0x1D1D1B,bool serif=false)=>new(){Text=text,FontSize=size,FontFamily=serif?Serif:Sans,Foreground=Brush(color),TextWrapping=TextWrapping.Wrap};
    private static Button Button(string label,Action action,bool primary=false){var b=new Button{Content=Text(label,12,primary?0xFFFFFFu:0x1D1D1Bu),Height=34,Padding=new Thickness(16,0,16,0),Background=Brush(primary?0x1D1D1Bu:0xFFFFFFu),BorderBrush=Brush(primary?0x1D1D1Bu:0xE4E4E0u),CornerRadius=new CornerRadius(6)};b.Click+=(_,_)=>action();return b;}
    private static Border Card(UIElement content,uint color=0xFFFFFF,int radius=14)=>new(){Child=content,Padding=new Thickness(18),Background=Brush(color),BorderBrush=Brush(0xE6E6E2),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(radius)};
    private static string Date(string? raw,bool time=false)=>CareerApplication.Date(raw??"")?.ToLocalTime().ToString(time?"MM.dd HH:mm":"MM.dd")??"—";
    public CareerApplicationDetailPage(CareerApplication item,Action back,Action<string,CareerApplication> perform){_seed=_item=item;_back=back;_perform=perform;Content=new ScrollViewer{Content=_page};Loaded+=async(_,_)=>await RefreshAsync();Unloaded+=(_,_)=>_life.Cancel();Render();}
    public async Task RefreshAsync(){_loading=true;_error=null;Render();try{
        var detail=await App.Session.Api.CareerRequestAsync("/api/job-applications/"+_seed.Id,ct:_life.Token);
        var all=new List<JsonNode>();string cursor="";var seen=new HashSet<string>();
        do{var query=new Dictionary<string,string>{{"application_id",_seed.Id},{"limit","500"},{"include_archived","true"}};if(cursor!="")query["cursor"]=cursor;var page=await App.Session.Api.CareerRequestAsync("/api/interview-sessions",query:query,ct:_life.Token);all.AddRange((page["items"]?.AsArray()??[]).Where(x=>x is not null).Select(x=>x!));cursor=page["next_cursor"]?.GetValue<string>()??"";if(cursor!=""&&!seen.Add(cursor))throw new InvalidDataException();}while(cursor!="");
        _life.Token.ThrowIfCancellationRequested();_sessions=all.OrderBy(x=>x["start_at"]?.GetValue<string>()).ToList();_item=new CareerApplication(detail["application"]!).IncludingSessions(all);
    }catch(OperationCanceledException){return;}catch(Exception e){_error=JobsBoardPage.Explain(e);}finally{_loading=false;}Render();}
    private void Render(){_page.Children.Clear();var breadcrumb=Button("← 岗位看板 / "+_item.Company,_back);breadcrumb.BorderThickness=new Thickness(0);breadcrumb.Padding=new Thickness(0);breadcrumb.HorizontalAlignment=HorizontalAlignment.Left;_page.Children.Add(breadcrumb);
        var header=new Grid{ColumnSpacing=20};header.ColumnDefinitions.Add(new ColumnDefinition());header.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var heading=new StackPanel{Spacing=12};heading.Children.Add(Text(_item.Company+" · "+_item.Title,28,serif:true));heading.Children.Add(Text((_item.Category==""?"":_item.CategoryLabel+" · ")+Date(_item.Text("created_at"))+" 导入",12,0x96968F));header.Children.Add(heading);
        var controls=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};controls.Children.Add(Button("岗位详情",()=>_=ShowJobAsync()));var menu=new MenuFlyout();void Entry(string label,string kind){var e=new MenuFlyoutItem{Text=label};e.Click+=(_,_)=>_perform(kind,_item);menu.Items.Add(e);}Entry("修改求职分类","category");Entry("编辑备注","notes");if(_item.Stage=="offer"&&!_item.Ended){Entry("修改 Offer 信息","offer");if(_item.Text("offer_status")=="received")Entry("婉拒 Offer","decline");}if(!_item.Ended)Entry(_item.Stage=="pending"?"不投了":"结束本次求职","terminate");Entry(_item.Text("archived_at")==""?"归档岗位":"恢复岗位",_item.Text("archived_at")==""?"archive":"restore");if(_item.Ended)Entry("删除岗位","delete");controls.Children.Add(new Button{Content="⋯",Flyout=menu});Grid.SetColumn(controls,1);header.Children.Add(controls);_page.Children.Add(header);
        if(_loading)_page.Children.Add(new ProgressRing{IsActive=true,Width=24,Height=24});if(_error is not null)_page.Children.Add(Button(_error+" · 重试",()=>_=RefreshAsync()));
        var pipeline=new StackPanel{Spacing=14};pipeline.Children.Add(Text("求职进度",14));var track=new Grid{ColumnSpacing=6};var steps=CareerProgress.Steps(_item);for(var i=0;i<steps.Length;i++){var step=steps[i];track.ColumnDefinitions.Add(new ColumnDefinition());var column=new StackPanel{Spacing=8};column.Children.Add(Text((step.State=="current"?"◉":step.State=="completed"?"✓":"○")+(i<steps.Length-1?" ─────":""),18,step.State=="current"?0x3F6FD8u:0xBBBBB5u));column.Children.Add(Text(step.Label,13,step.State=="current"?0x3F6FD8u:0x96968Fu));column.Children.Add(Text(step.Date==""?" ":Date(step.Date),11,0x96968F));Grid.SetColumn(column,i);track.Children.Add(column);}pipeline.Children.Add(track);_page.Children.Add(Card(pipeline,0xFAFAF9));
        var flow=CareerFlow.For(_item);var next=new Grid{ColumnSpacing=20};next.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(88)});next.ColumnDefinitions.Add(new ColumnDefinition());next.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var tile=new StackPanel{Spacing=8,VerticalAlignment=VerticalAlignment.Center};tile.Children.Add(Text(_item.StageLabel,15));tile.Children.Add(Text(_item.StatusLabel,10,0x96968F));next.Children.Add(new Border{Child=tile,Height=88,Padding=new Thickness(12),Background=Brush(0xF0F0EC),CornerRadius=new CornerRadius(12)});var copy=new StackPanel{Spacing=8,VerticalAlignment=VerticalAlignment.Center};copy.Children.Add(Text("下一步",11,0x96968F));copy.Children.Add(Text(flow.Headline,19));copy.Children.Add(Text(flow.Explanation,13,0x55554F));Grid.SetColumn(copy,1);next.Children.Add(copy);var primary=Button(flow.Button,()=>{if(flow.Kind is "history" or "records"){var latest=_sessions.LastOrDefault(x=>x["status"]?.GetValue<string>()!="cancelled"&&(flow.Kind=="history"||x["application_stage_id"]?.GetValue<string>()==_item.Raw["current_stage"]?["id"]?.GetValue<string>()));if(latest is not null)_=ShowRecordAsync(latest);else if(Content is ScrollViewer viewer)viewer.ChangeView(null,Math.Min(400,viewer.ScrollableHeight),null);}else _perform(flow.Kind,_item);},true);primary.IsEnabled=!_loading&&_error is null&&(flow.Kind!="records"||_sessions.Count>0);primary.VerticalAlignment=VerticalAlignment.Center;Grid.SetColumn(primary,2);next.Children.Add(primary);_page.Children.Add(Card(next,radius:16));
        var lower=new Grid{ColumnSpacing=24};lower.ColumnDefinitions.Add(new ColumnDefinition());lower.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(276)});var history=new StackPanel{Spacing=14};history.Children.Add(Text("阶段记录",14));var stages=_item.Raw["stages"]?.AsArray()??[];if(stages.Count==0)history.Children.Add(Text("还没有阶段记录。记录投递后，会在这里留下求职进程。",12,0x96968F));foreach(var raw in stages.Reverse()){if(raw is null)continue;var card=new StackPanel{Spacing=14};card.Children.Add(Text(raw["stage_label"]?.GetValue<string>()??"",14));card.Children.Add(Text(Date(raw["entered_at"]?.GetValue<string>())+" · "+(_item.Ended?"已结束":raw["stage_status"]?.GetValue<string>()=="completed"?"已完成":"当前阶段"),11,0x96968F));foreach(var entry in _sessions.Where(x=>x["application_stage_id"]?.GetValue<string>()==raw["id"]?.GetValue<string>()))card.Children.Add(Button(Date(entry["start_at"]?.GetValue<string>(),true)+" · 查看记录 →",()=>_=ShowRecordAsync(entry)));if(raw["stage_type"]?.GetValue<string>()=="offer"){card.Children.Add(Text(_item.Text("offer_status")=="none"?"OC · 口头意向":"正式 Offer"));if(_item.Text("offer_salary")!="")card.Children.Add(Text("薪资："+_item.Text("offer_salary")+" "+_item.Text("offer_salary_currency")));if(_item.Text("offer_base_location")!="")card.Children.Add(Text("工作地点："+_item.Text("offer_base_location")));}history.Children.Add(Card(card));}lower.Children.Add(history);
        var side=new StackPanel{Spacing=14};var info=new StackPanel{Spacing=12};info.Children.Add(Text("投递信息",13));info.Children.Add(Text("投递日期    "+Date(_item.Text("applied_at")),12,0x55554F));info.Children.Add(Text("简历    "+(_item.Text("resume_id")==""?"未关联":"已关联简历"),12,0x55554F));if(_item.Text("notes")!="")info.Children.Add(Text(_item.Text("notes"),12,0x55554F));info.Children.Add(Button("编辑备注",()=>_perform("notes",_item)));side.Children.Add(Card(info));var assets=new StackPanel{Spacing=12};assets.Children.Add(Text("关联资料",13));assets.Children.Add(Text("在各轮记录中查看关联资料",12,0x96968F));side.Children.Add(Card(assets));Grid.SetColumn(side,1);lower.Children.Add(side);_page.Children.Add(lower);
    }
    private async Task ShowJobAsync(){try{var result=await App.Session.Api.CareerRequestAsync("/api/job-descriptions/"+_item.Text("job_description_id"),ct:_life.Token);_life.Token.ThrowIfCancellationRequested();await new ContentDialog{XamlRoot=XamlRoot,Title="岗位详情",Content=new ScrollViewer{Content=Text(result["job_description"]?["description"]?.GetValue<string>()??"暂无岗位描述"),MaxHeight=500},CloseButtonText="关闭"}.ShowAsync();}catch(Exception e){_error=JobsBoardPage.Explain(e);Render();}}
    private async Task ShowRecordAsync(JsonNode entry){try{var full=await App.Session.Api.CareerRequestAsync("/api/interview-sessions/"+entry["id"]!.GetValue<string>(),ct:_life.Token);_life.Token.ThrowIfCancellationRequested();var record=full["session"]!;var view=new StackPanel{Spacing=16,MinWidth=560};var summary=new TextBox{Header="面试记录 / 复盘笔记",Text=record["review_summary"]?.GetValue<string>()??"",AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=180};var questions=new TextBox{Header="问题记录",Text=record["questions_markdown"]?.GetValue<string>()??"",AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=100};var improvement=new TextBox{Header="复盘与改进",Text=record["improvement_markdown"]?.GetValue<string>()??"",AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=100};view.Children.Add(summary);view.Children.Add(questions);view.Children.Add(improvement);var error=Text("",12);view.Children.Add(error);var dialog=new ContentDialog{XamlRoot=XamlRoot,Title=record["stage_label"]?.GetValue<string>()+" · 记录与复盘",Content=new ScrollViewer{Content=view,MaxHeight=480},PrimaryButtonText="保存记录",SecondaryButtonText=record["status"]?.GetValue<string>()=="scheduled"?"标记已完成":"",CloseButtonText="关闭"};JsonObject? frozen=null;string? frozenCommand=null;async Task Write(ContentDialogButtonClickEventArgs args,string? command){var defer=args.GetDeferral();dialog.IsPrimaryButtonEnabled=dialog.IsSecondaryButtonEnabled=false;try{if(frozen is not null&&frozenCommand!=command){args.Cancel=true;error.Text="请重试上一次操作，或关闭后刷新确认状态。";return;}frozenCommand=command;frozen??=command is null?new JsonObject{["base_lock_version"]=record["lock_version"]!.GetValue<int>(),["review_summary"]=summary.Text,["questions_markdown"]=questions.Text,["improvement_markdown"]=improvement.Text}:new JsonObject{["base_lock_version"]=record["lock_version"]!.GetValue<int>()};summary.IsEnabled=questions.IsEnabled=improvement.IsEnabled=false;await App.Session.Api.CareerRequestAsync("/api/interview-sessions/"+record["id"]!.GetValue<string>()+(command is null?"":"/"+command),method:command is null?"PUT":"POST",body:frozen,ct:_life.Token);}catch(Exception e){args.Cancel=true;error.Text=JobsBoardPage.Explain(e);}finally{dialog.IsPrimaryButtonEnabled=frozen is null||frozenCommand is null;dialog.IsSecondaryButtonEnabled=frozen is null||frozenCommand=="complete";defer.Complete();}}dialog.PrimaryButtonClick+=async(_,e)=>await Write(e,null);dialog.SecondaryButtonClick+=async(_,e)=>await Write(e,"complete");await dialog.ShowAsync();await RefreshAsync();}catch(Exception e){_error=JobsBoardPage.Explain(e);Render();}}
}
