// 简历字段 key 目录：key 即 JSON 简历中的路径（数组分组省略下标），值是给决策模型看的描述。
// 描述写法：中文名；常见同义说法；英文。新增字段时同步补充 JSON 简历示例。
export const KEYS: Record<string, string> = {
  'basics.name': '姓名；中文姓名；真实姓名；full name; name',
  'basics.firstName': '名；名字；英文名；拼音名；first name; given name',
  'basics.lastName': '姓；姓氏；拼音姓；last name; surname; family name',
  'basics.firstNameZh': '中文名字（不含姓）；名-中文',
  'basics.lastNameZh': '中文姓氏；姓-中文',
  'basics.preferredName': '常用名；昵称；英文昵称；preferred name; nickname',
  'basics.gender': '性别；男女；gender; sex',
  'basics.birthDate': '出生日期；生日；出生年月；date of birth; birthday',
  'basics.ethnicity': '民族；ethnicity',
  'basics.nationality': '国籍；nationality; citizenship',
  'basics.maritalStatus': '婚姻状况；婚否；marital status',
  'basics.politicalStatus': '政治面貌；党员；团员；political status',
  'basics.idType': '证件类型；身份证件类型；ID type',
  'basics.idNumber': '证件号码；身份证号；护照号；ID number; passport number',
  'basics.hukou': '户口所在地；户籍；户籍所在地；household registration',
  'basics.hometown': '籍贯；老家；生源地；native place; hometown',
  'basics.gaokaoOrigin': '高考生源地；高考所在省份',
  'basics.heightCm': '身高（厘米）；height',
  'basics.weightKg': '体重（公斤）；weight',
  'contact.phone': '手机号码；手机；联系电话；移动电话；mobile phone; phone number',
  'contact.altPhone': '备用电话；其他联系电话；alternative phone',
  'contact.emergencyPhone': '紧急联系人电话；emergency contact phone',
  'contact.dialCode': '国家或地区电话区号；国际区号；country code; dial code',
  'contact.email': '电子邮箱；邮箱；email address',
  'contact.city': '现居城市；所在城市；当前所在地；current city; current location',
  'contact.address': '通讯地址；家庭住址；详细地址；address line',
  'contact.country': '国家/地区；居住国家；country',
  'education.school': '学校名称；毕业院校；就读学校；大学；school; university; college',
  'education.major': '专业；所学专业；专业名称；major; field of study',
  'education.degree': '学历；最高学历；学历层次；本科/硕士/博士；education level',
  'education.degreeTitle': '学位；学士/硕士/博士学位；degree',
  'education.enrollDate': '入学时间；教育经历开始时间；就读开始日期；start date of study',
  'education.gradDate': '毕业时间；教育经历结束时间；预计毕业日期；graduation date; end date of study',
  'education.gpa': 'GPA；绩点；平均学分绩点；grade point average',
  'education.rank': '成绩排名；专业排名；class rank',
  'education.trainingMode': '培养方式；学习形式；全日制/非全日制；study mode',
  'education.studentNumber': '学号；student ID',
  'work.company': '工作单位；公司名称；雇主；employer; company',
  'work.title': '职位名称；职位；岗位；职务；job title; position',
  'work.startDate': '工作开始时间；入职时间；工作经历开始日期；employment start date',
  'work.endDate': '工作结束时间；离职时间；工作经历结束日期；employment end date',
  'work.summary': '工作内容；工作职责；工作描述；job responsibilities; description',
  'work.salary': '当前薪资；目前薪资；税前月薪；current salary',
  'work.city': '工作地点；工作城市；work location',
  'internship.company': '实习单位；实习公司；internship company',
  'internship.title': '实习岗位；实习职位；internship position',
  'internship.startDate': '实习开始时间；internship start date',
  'internship.endDate': '实习结束时间；internship end date',
  'internship.summary': '实习内容；实习职责；internship description',
  'internship.salary': '实习薪资；internship salary',
  'projects.name': '项目名称；project name',
  'projects.role': '项目角色；项目职责；担任职务；project role',
  'projects.description': '项目描述；项目内容；project description',
  'awards.title': '奖项名称；获奖情况；荣誉名称；award name; honor',
  'languages.language': '语言；外语语种；语言类型；language',
  'languages.cert': '外语证书；语言成绩；英语等级；CET-6；IELTS；TOEFL；language certificate',
  'skills.domain': '技能；专业技能；技能特长；skills',
  'family.name': '家庭成员姓名；父亲姓名；母亲姓名；family member name',
  'family.relation': '与本人关系；家庭成员关系；relationship',
  'family.employer': '家庭成员工作单位；父母工作单位；family member employer',
  'family.position': '家庭成员职务；父母职务；family member position',
  'family.phone': '家庭成员联系电话；父母电话；family member phone',
  'intent.position': '应聘职位；意向岗位；申请职位；desired position',
  'intent.cities': '期望工作城市；意向城市；期望工作地点；preferred work location',
  'intent.interviewCity': '期望面试地点；面试城市；interview location',
  'intent.salary': '期望薪资；期望月薪；expected salary',
  'intent.acceptRelocation': '是否接受调剂；是否服从调配；accept reassignment',
  'intent.availableDate': '到岗时间；最快到岗日期；可入职时间；available start date',
  'intent.channel': '获知招聘信息的渠道；如何了解到本次招聘；信息来源；how did you hear about us',
  'intent.referralCode': '内推码；推荐码；referral code',
  'others.personalSite': '个人主页；个人网站；博客；personal website',
  'others.portfolio': '作品集链接；GitHub；portfolio link',
  'records.dossierLocation': '档案所在地；人事档案存放单位',
  'records.noCriminal': '有无犯罪记录；无违法犯罪声明',
  'hkGlobal.workAuth': '工作签证；工作许可；是否有当地工作权；work authorization',
  'hkGlobal.needSponsorship': '是否需要签证担保；need visa sponsorship',
  'hkGlobal.noticePeriod': '离职通知期；notice period',
  'basics.age': '年龄；age',
  'basics.englishName': '英文名；English name',
  'contact.wechat': '微信号；WeChat ID',
  'contact.qq': 'QQ号',
  'contact.postcode': '邮政编码；邮编；postal code',
  'contact.emergencyName': '紧急联系人姓名；emergency contact name',
  'education.city': '学校所在城市；school location',
  'education.courses': '主修课程；核心课程；courses',
  'education.advisor': '导师姓名；supervisor',
  'work.department': '所在部门；department',
  'work.reportTo': '汇报对象；直属上级；reports to',
  'work.leaveReason': '离职原因；reason for leaving',
  'internship.department': '实习部门',
  'projects.startDate': '项目开始时间；project start date',
  'projects.endDate': '项目结束时间；project end date',
  'projects.link': '项目链接；project URL',
  'awards.date': '获奖时间；award date',
  'awards.level': '获奖级别；国家级/省级/校级',
  'certificates.name': '证书名称；资格证书；certificate',
  'certificates.date': '证书获得时间；发证日期',
  'languages.level': '语言掌握程度；熟练程度；听说读写能力；proficiency',
  'others.selfEvaluation': '自我评价；自我介绍；个人简介；about me',
  'others.hobbies': '兴趣爱好；特长；hobbies',
  'intent.jobType': '求职类型；全职/实习；job type',
  'intent.industry': '期望行业；industry',
  'intent.workExperience': '工作年限；工作经验年数；years of experience',
};

// 这些分组在 JSON 简历中是数组，字段路径形如 education.0.school。
export const LIST_GROUPS = ['education', 'work', 'internship', 'projects', 'awards', 'certificates', 'languages', 'family'] as const;
export type ListGroup = (typeof LIST_GROUPS)[number];

export const isListGroup = (group: string): group is ListGroup => (LIST_GROUPS as readonly string[]).includes(group);

const DATE_SUFFIX = /(Date|enrollDate|gradDate)$/;
export const isDateKey = (key: string) => DATE_SUFFIX.test(key);

// 开始/结束成对的日期 key，用于“起止时间”这类同标签字段按先后顺序纠正。
export const START_END_PAIRS: Record<string, string> = {
  'education.enrollDate': 'education.gradDate',
  'work.startDate': 'work.endDate',
  'internship.startDate': 'internship.endDate',
  'projects.startDate': 'projects.endDate',
};

export const GROUP_LABELS: Record<ListGroup, string> = {
  education: '教育',
  work: '工作',
  internship: '实习',
  projects: '项目',
  awards: '获奖',
  certificates: '证书',
  languages: '语言',
  family: '家庭成员',
};
