import type { MockInterviewDetail, MockInterviewQuestion, MockInterviewReport } from "../mockInterviewApi";
export function question(overrides: Partial<MockInterviewQuestion> = {}): MockInterviewQuestion {
  return { id: "101", parent_id: null, sequence_no: 1, kind: "main", plan_index: 0, depth_level: 2, content: "请介绍项目里的缓存设计。", answer_status: "pending", answer_text: null, answered_at: null, evaluation: null, answer_source: null, audio_duration_ms: null, has_recording: false, raw_transcript: null, transcript_state: null, correction: null, re_evaluate_count: 0, evaluation_history: null, ...overrides };
}
export function report(): MockInterviewReport {
  return { rubric_version: "v2", answer_mode: "text", voice_metrics: null, headline: "缓存原理清楚，边界需要补充", summary: "能说明方案取舍。", total_score: 75, question_average: 75, dimension_score: 75, dimensions: ["professional_depth", "structure", "job_fit", "resume_consistency", "communication"].map((key) => ({ key: key as MockInterviewReport["dimensions"][number]["key"], score: 3.5, weight: .2, evidence: ["回答中的方案"], comment: "继续练习" })), questions: [{ topic: "缓存设计", sequence_no: 1, skipped: false, score: 75, achieved_depth: 2, signals: [], factual_errors: [], highlights: ["能解释取舍"], weaknesses: ["缺少边界"], reference_answer: "结合一致性和成本说明缓存方案。" }], fact_check: { status: "not_requested", items: [] }, resume_risks: [], improvements: ["补充缓存失效场景"], off_topic_detected: false, low_confidence: false };
}
export function interview(overrides: Partial<MockInterviewDetail> = {}): MockInterviewDetail {
  return { id: "10", status: "in_progress", source_type: "resume", job_application_id: null, resume_id: "1", job_description_id: null, repeat_of_id: null, resume_title: "张三的简历", company_name: null, job_title: null, target_role: "后端工程师", stage_label: null, interview_type: "technical", difficulty: "intermediate", question_count: 3, follow_up_enabled: true, language: "zh", answer_mode: "text", materials_in_questions: false, total_score: null, low_confidence: false, error_code: null, started_at: "2026-09-30T10:00:00Z", finished_at: null, created_at: "2026-09-30T09:59:00Z", lock_version: 1, materials: [], current_question_id: "101", answered_main_questions: 0, needs_reply: false, questions: [question()], report: null, transcript_corrected_at: null, recordings_deleted: false, ...overrides };
}
export function completedVoice(): MockInterviewDetail {
  const evaluation = report().questions[0];
  return interview({ status: "completed", answer_mode: "voice", total_score: 75, current_question_id: null, answered_main_questions: 1, finished_at: "2026-09-30T10:10:00Z", questions: [question({ answer_status: "answered", answer_source: "voice", answer_text: "我用缓存减少数据库读压力，也考虑过缓存失效的情况。", raw_transcript: "我用缓存减少数据库读压力，也考虑过缓存失效的情况。", transcript_state: "original", audio_duration_ms: 60_000, has_recording: true, evaluation })], report: { ...report(), answer_mode: "voice", voice_metrics: { chars_per_minute: 200, long_pauses: 1, filler_ratio: .01, answer_duration_ms: 60_000, reference: { chars_per_minute: [180, 260], long_pauses: [0, 3], filler_ratio: [0, .05] }, tip: "保持语速" } } });
}
