"""Curated official entries. Pending entries cannot be enabled as working adapters."""
from dataclasses import dataclass

from linkresume.application.job_pool.types import SourceConfig
from linkresume.core.errors import ApiError


@dataclass(frozen=True)
class CompanySource:
    key: str
    name: str
    adapter: str
    host: str
    portals: tuple[str, ...]
    url: str
    site_id: int | None = None
    channels: tuple[str, ...] = ()
    portal_type: int = 2  # Tenant metadata, not an administrator-controlled endpoint parameter.

    def config(self):
        return SourceConfig(host=self.host, portals=list(self.portals), site_id=self.site_id).model_dump()


CATALOG = (
    CompanySource("tencent", "腾讯", "tencent", "careers.tencent.com", ("social",), "https://careers.tencent.com/", channels=("experienced",)),
    CompanySource("bytedance", "字节跳动", "feishu", "jobs.bytedance.com", ("default", "campus"), "https://jobs.bytedance.com/", channels=("experienced", "campus", "internship")),
    CompanySource("minimax", "MiniMax", "feishu", "vrfi1sk8a0.jobs.feishu.cn", ("index",), "https://vrfi1sk8a0.jobs.feishu.cn/", channels=("experienced",)),
    CompanySource("meituan", "美团", "meituan", "zhaopin.meituan.com", ("social", "campus", "intern"), "https://zhaopin.meituan.com/", channels=("experienced", "campus", "internship")),
    CompanySource("moonshot", "月之暗面", "moka", "moonshot", ("social",), "https://app.mokahr.com/social-recruitment/moonshot/148506", site_id=148506, channels=("experienced",)),
    CompanySource("baidu", "百度", "baidu", "talent.baidu.com", ("SOCIAL", "GRADUATE", "INTERN"), "https://talent.baidu.com/", channels=("experienced", "campus", "internship")),
    CompanySource("jd", "京东", "jd", "zhaopin.jd.com", ("3",), "https://zhaopin.jd.com/", channels=("experienced",)),
    CompanySource("netease", "网易", "netease", "hr.163.com", ("social",), "https://hr.163.com/", channels=("experienced",)),
    CompanySource("alibaba", "阿里巴巴", "alibaba", "campus-talent.alibaba.com", ("campus", "intern"), "https://campus-talent.alibaba.com/", channels=("campus", "internship")),
    CompanySource("kuaishou", "快手", "kuaishou", "campus.kuaishou.cn", ("campus",), "https://campus.kuaishou.cn/", channels=("campus",)),
    CompanySource("xiaohongshu", "小红书", "xiaohongshu", "job.xiaohongshu.com", ("social", "campus", "intern"), "https://job.xiaohongshu.com/", channels=("experienced", "campus", "internship")),
    CompanySource("bilibili", "哔哩哔哩", "bilibili", "jobs.bilibili.com", ("social", "campus", "intern"), "https://jobs.bilibili.com/", channels=("experienced", "campus", "internship")),
    CompanySource("pdd", "拼多多", "pdd", "careers.pddglobalhr.com", ("campus", "intern"), "https://careers.pddglobalhr.com/campus/grad", channels=("campus", "internship")),
    CompanySource("didi", "滴滴", "didi", "talent.didiglobal.com", ("social",), "https://talent.didiglobal.com/home/", channels=("experienced",)),
    CompanySource("ctrip", "携程", "ctrip", "job.ctrip.com", ("social", "campus", "intern"), "https://job.ctrip.com/", channels=("experienced", "campus", "internship")),
    CompanySource("xiaomi", "小米", "feishu", "xiaomi.jobs.f.mioffice.cn", ("index", "campus", "internship"), "https://xiaomi.jobs.f.mioffice.cn/index", channels=("experienced", "campus", "internship"), portal_type=6),
    CompanySource("ant", "蚂蚁集团", "ant", "talent.antgroup.com", ("social", "campus"), "https://talent.antgroup.com/", channels=("experienced", "campus", "internship")),
    CompanySource("mihoyo", "米哈游", "mihoyo", "jobs.mihoyo.com", ("social", "campus", "intern"), "https://jobs.mihoyo.com/", channels=("experienced", "campus", "internship")),
    CompanySource("dewu", "得物", "feishu", "careers.dewu.com", ("index",), "https://careers.dewu.com/", channels=("experienced", "internship")),
    CompanySource("dewu-campus", "得物", "feishu", "campus.dewu.com", ("578078",), "https://campus.dewu.com/578078", channels=("campus",)),
    CompanySource("zhipu", "智谱", "feishu", "zhipu-ai.jobs.feishu.cn", ("index",), "https://zhipu-ai.jobs.feishu.cn/", channels=("experienced", "internship")),
    CompanySource("lilith", "莉莉丝", "feishu", "lilithgames.jobs.feishu.cn", ("index",), "https://lilithgames.jobs.feishu.cn/", channels=("experienced",)),
    CompanySource("kurogame", "库洛游戏", "feishu", "kurogame.jobs.feishu.cn", ("index",), "https://kurogame.jobs.feishu.cn/", channels=("experienced",)),
    CompanySource("moonton", "沐瞳科技", "feishu", "moonton.jobs.feishu.cn", ("index",), "https://moonton.jobs.feishu.cn/", channels=("experienced",)),
    CompanySource("01ai", "零一万物", "feishu", "01ai.jobs.feishu.cn", ("index",), "https://01ai.jobs.feishu.cn/", channels=("experienced",)),
    CompanySource("deepseek", "DeepSeek", "moka", "high-flyer", ("social",), "https://app.mokahr.com/social-recruitment/high-flyer/140576", site_id=140576, channels=("experienced",)),
    CompanySource("shengshu", "生数科技", "feishu", "shengshu.jobs.feishu.cn", ("index",), "https://shengshu.jobs.feishu.cn/index", channels=("experienced",)),
    CompanySource("dcar", "懂车帝", "feishu", "dcar.jobs.feishu.cn", ("index",), "https://dcar.jobs.feishu.cn/index", channels=("experienced",)),
    CompanySource("thundersoft", "中科创达", "feishu", "thundersoft.jobs.feishu.cn", ("index",), "https://thundersoft.jobs.feishu.cn/index", channels=("experienced",)),
    CompanySource("metaapp", "MetaApp", "feishu", "meta.jobs.feishu.cn", ("index",), "https://meta.jobs.feishu.cn/index", channels=("experienced",)),
    CompanySource("xdinc", "心动网络", "feishu", "xd-legacy.jobs.feishu.cn", ("index",), "https://xd-legacy.jobs.feishu.cn/index", channels=("experienced",)),
    CompanySource("wepie", "微派网络", "feishu", "wepie.jobs.feishu.cn", ("index",), "https://wepie.jobs.feishu.cn/index", channels=("experienced",)),
    CompanySource("maimai", "脉脉", "feishu", "maimai.jobs.feishu.cn", ("index",), "https://maimai.jobs.feishu.cn/index", channels=("experienced",)),
    CompanySource("zego", "即构科技", "feishu", "zegocloud.jobs.feishu.cn", ("index",), "https://zegocloud.jobs.feishu.cn/index", channels=("experienced",)),
    CompanySource("blacklake", "黑湖科技", "feishu", "blacklake.jobs.feishu.cn", ("index",), "https://blacklake.jobs.feishu.cn/index", channels=("experienced",)),
    CompanySource("cider", "Cider", "feishu", "ciderglobal.jobs.feishu.cn", ("index",), "https://ciderglobal.jobs.feishu.cn/index", channels=("experienced",)),
    CompanySource("bluefocus", "蓝色光标", "feishu", "bluefocus.jobs.feishu.cn", ("index",), "https://bluefocus.jobs.feishu.cn/index", channels=("experienced",)),
    CompanySource("lizhi", "荔枝", "feishu", "lizhi2021.jobs.feishu.cn", ("index",), "https://lizhi2021.jobs.feishu.cn/index", channels=("experienced",)),
    CompanySource("dianhun", "电魂网络", "moka", "dianhun", ("social",), "https://app.mokahr.com/social-recruitment/dianhun/55952", site_id=55952, channels=("experienced",)),
    CompanySource("kingnet", "恺英网络", "moka", "kingnet", ("social",), "https://app.mokahr.com/social-recruitment/kingnet/2247", site_id=2247, channels=("experienced",)),
    CompanySource("shengqu", "盛趣游戏", "moka", "shengqu", ("social",), "https://app.mokahr.com/social-recruitment/shengqu/4077", site_id=4077, channels=("experienced",)),
    CompanySource("yoozoo", "游族网络", "moka", "yoozoo", ("social",), "https://app.mokahr.com/social-recruitment/yoozoo/91950", site_id=91950, channels=("experienced",)),
    CompanySource("leyuansu", "乐元素", "moka", "leyuansu", ("social",), "https://app.mokahr.com/social-recruitment/leyuansu/2358", site_id=2358, channels=("experienced",)),
    CompanySource("micateam", "散爆网络", "moka", "micateam", ("social",), "https://app.mokahr.com/social-recruitment/micateam/142158", site_id=142158, channels=("experienced",)),
    CompanySource("shein", "SHEIN希音", "moka", "shein", ("social",), "https://app.mokahr.com/social-recruitment/shein/2933", site_id=2933, channels=("experienced",)),
    CompanySource("stepfun", "阶跃星辰", "moka", "step", ("social",), "https://app.mokahr.com/social-recruitment/step/94904", site_id=94904, channels=("experienced",)),
    CompanySource("dolphindb", "DolphinDB", "moka", "dolphindb", ("social",), "https://app.mokahr.com/social-recruitment/dolphindb/37785", site_id=37785, channels=("experienced",)),
    CompanySource("xunlei", "迅雷", "moka", "xunlei", ("social",), "https://app.mokahr.com/social-recruitment/xunlei/26599", site_id=26599, channels=("experienced",)),
    CompanySource("zuoyebang", "作业帮", "moka", "zuoyebang", ("social",), "https://app.mokahr.com/social-recruitment/zuoyebang/41328", site_id=41328, channels=("experienced",)),
    CompanySource("sina", "新浪微博", "moka", "sina", ("social",), "https://app.mokahr.com/social-recruitment/sina/43535", site_id=43535, channels=("experienced",)),
    CompanySource("manbang", "满帮集团", "moka", "manbang", ("social",), "https://app.mokahr.com/social-recruitment/manbang/46269", site_id=46269, channels=("experienced",)),
    CompanySource("eastmoney", "东方财富", "moka", "eastmoney", ("social",), "https://app.mokahr.com/social-recruitment/eastmoney/57970", site_id=57970, channels=("experienced",)),
    CompanySource("taotian", "淘天集团", "alibaba-cpo", "talent.taotian.com", ("social",), "https://talent.taotian.com/off-campus/position-list", channels=("experienced",)),
    CompanySource("eleme", "饿了么", "alibaba-cpo", "talent.ele.me", ("social",), "https://talent.ele.me/off-campus/position-list", channels=("experienced",)),
    CompanySource("fliggy", "飞猪", "alibaba-cpo", "career.fliggy.com", ("social",), "https://career.fliggy.com/off-campus/position-list", channels=("experienced",)),
    CompanySource("aidc", "阿里国际数字商业", "alibaba-cpo", "aidc-jobs.alibaba.com", ("social",), "https://aidc-jobs.alibaba.com/off-campus/position-list", channels=("experienced",)),
    CompanySource("tongyi", "通义实验室", "alibaba-cpo", "careers-tongyi.alibaba.com", ("social",), "https://careers-tongyi.alibaba.com/off-campus/position-list", channels=("experienced",)),
    CompanySource("aliyun", "阿里云", "alibaba-cpo", "careers.aliyun.com", ("social",), "https://careers.aliyun.com/off-campus/position-list", channels=("experienced",)),
    CompanySource("dingtalk", "钉钉", "alibaba-cpo", "talent.dingtalk.com", ("social",), "https://talent.dingtalk.com/off-campus/position-list", channels=("experienced",)),
    CompanySource("quark", "夸克", "alibaba-cpo", "talent.quark.cn", ("social",), "https://talent.quark.cn/off-campus/position-list", channels=("experienced",)),
    CompanySource("amap", "高德", "alibaba-cpo", "talent.amap.com", ("social",), "https://talent.amap.com/off-campus/position-list", channels=("experienced",)),
    CompanySource("hujing", "虎鲸文娱", "alibaba-cpo", "jobs.hujing-dme.com", ("social",), "https://jobs.hujing-dme.com/off-campus/position-list", channels=("experienced",)),
    CompanySource("lingxi", "灵犀互娱", "alibaba-cpo", "talent.lingxigames.com", ("social",), "https://talent.lingxigames.com/off-campus/position-list", channels=("experienced",)),
    CompanySource("alihealth", "阿里健康", "alibaba-cpo", "careers.alihealth.cn", ("social",), "https://careers.alihealth.cn/off-campus/position-list", channels=("experienced",)),
    CompanySource('huolala', '货拉拉', "beisen", 'join.huolala.cn', ('1',), "https://join.huolala.cn/", channels=('experienced',)),
    CompanySource('ke', '贝壳', "beisen", 'join.ke.com', ('1',), "https://join.ke.com/", channels=('experienced',)),
    CompanySource('ke-campus', '贝壳', "beisen", 'campuske.zhiye.com', ('1', '2'), "https://campuske.zhiye.com/", channels=('experienced', 'campus')),
    CompanySource('iqiyi', '爱奇艺', "beisen", 'iqiyi.zhiye.com', ('1',), "https://iqiyi.zhiye.com/", channels=('experienced',)),
    CompanySource('360-campus', '360', "beisen", '360campus.zhiye.com', ('2',), "https://360campus.zhiye.com/", channels=('campus',)),
    CompanySource('iflytek', '科大讯飞', "beisen", 'iflytek.zhiye.com', ('1', '2'), "https://iflytek.zhiye.com/", channels=('experienced', 'campus')),
    CompanySource('hellobike', '哈啰', "beisen", 'hellobike.zhiye.com', ('1', '2'), "https://hellobike.zhiye.com/", channels=('experienced', 'campus')),
    CompanySource("huawei", "华为", "huawei", "career.huawei.com", ("SR",), "https://career.huawei.com/cn/social-recruitment-job-list", channels=("experienced",)),
    CompanySource("dji", "大疆", "dji", "we.dji.com", ("N", "Y"), "https://we.dji.com/zh-CN/campus", channels=("experienced", "internship")),
    CompanySource("jd-campus", "京东", "jd-campus", "campus.jd.com", ("present", "internship"), "https://campus.jd.com/", channels=("campus", "internship")),
    CompanySource("netease-campus", "网易", "netease-campus", "campus.163.com", ("69",), "https://campus.163.com/", channels=("campus",)),
    CompanySource("zhihu", "知乎", "moka", "zhihu", ("social",), "https://app.mokahr.com/apply/zhihu/78336", site_id=78336, channels=("experienced",)),
    CompanySource("kuaishou-social", "快手", "kuaishou-social", "zhaopin.kuaishou.cn", ("social", "intern"), "https://zhaopin.kuaishou.cn/recruit/e/", channels=("experienced", "internship")),
    CompanySource("lenovo", "联想", "lenovo", "talent.lenovo.com.cn", ("1", "2", "3"), "https://talent.lenovo.com.cn/", channels=("campus", "internship")),
    CompanySource("hypergryph", "鹰角网络", "moka", "hypergryph", ("social",), "https://jobs.hypergryph.com/apply/hypergryph/26325/", site_id=26325, channels=("experienced",)),
    CompanySource("yuewen", "阅文集团", "beisen", "yuewen.zhiye.com", ("1",), "https://yuewen.zhiye.com/", channels=("experienced",)),
    CompanySource("sohu", "搜狐", "moka", "sohu", ("campus",), "https://app.mokahr.com/campus_apply/sohu/5682", site_id=5682, channels=("campus",)),
    CompanySource("tme", "腾讯音乐", "tme", "join.tencentmusic.com", ("social", "campus"), "https://join.tencentmusic.com/jobs/list/", channels=("experienced", "campus", "internship")),
    CompanySource("aibee", "爱笔智能", "feishu", "aibee.jobs.feishu.cn", ('index',), "https://aibee.jobs.feishu.cn/index", channels=('experienced',)),
    CompanySource("shixiang", "拾象科技", "feishu", "shixiangtech.jobs.feishu.cn", ('index',), "https://shixiangtech.jobs.feishu.cn/index", channels=('experienced',)),
    CompanySource("boomingtech", "BoomingTech", "feishu", "boomingtech.jobs.feishu.cn", ('index',), "https://boomingtech.jobs.feishu.cn/index", channels=('experienced',)),
    CompanySource("eyugame", "易娱网络", "moka", "eyugame", ('social',), "https://app.mokahr.com/social-recruitment/eyugame/47373", site_id=47373, channels=('experienced',)),
    CompanySource("bole", "博乐科技", "moka", "bolegames", ('social',), "https://app.mokahr.com/social-recruitment/bolegames/37642", site_id=37642, channels=('experienced',)),
    CompanySource("lovegames", "乐府互娱", "moka", "lovegames", ('social',), "https://app.mokahr.com/social-recruitment/lovegames/21946", site_id=21946, channels=('experienced',)),
    CompanySource("shiyue", "诗悦网络", "moka", "shiyuehr", ('social',), "https://app.mokahr.com/social-recruitment/shiyuehr/72054", site_id=72054, channels=('experienced',)),
    CompanySource("shangyou", "尚游游戏", "moka", "shangyou", ('social',), "https://app.mokahr.com/social-recruitment/shangyou/42165", site_id=42165, channels=('experienced',)),
    CompanySource("smartmore", "思谋科技", "moka", "smartmore", ('social',), "https://app.mokahr.com/social-recruitment/smartmore/40505", site_id=40505, channels=('experienced',)),
    CompanySource("baichuan", "百川智能", "feishu", "cq6qe6bvfr6.jobs.feishu.cn", ('baichuanzhaopin',), "https://cq6qe6bvfr6.jobs.feishu.cn/", channels=('experienced',)),
    CompanySource("modelbest", "面壁智能", "feishu", "modelbest.jobs.feishu.cn", ('career',), "https://modelbest.jobs.feishu.cn/", channels=('experienced',)),
    CompanySource("infinigence", "无问芯穹", "feishu", "infinigence.jobs.feishu.cn", ('infinigence',), "https://infinigence.jobs.feishu.cn/", channels=('experienced',)),
    CompanySource("aisphere", "爱诗科技", "feishu", "aisphere.jobs.feishu.cn", ('join',), "https://aisphere.jobs.feishu.cn/", channels=('experienced',)),
    CompanySource("juzibot", "句子互动", "feishu", "juzihudong.jobs.feishu.cn", ('juzibot',), "https://juzihudong.jobs.feishu.cn/", channels=('experienced',)),
    CompanySource("dedao", "得到", "feishu", "dedao.jobs.feishu.cn", ('shezhao',), "https://dedao.jobs.feishu.cn/", channels=('experienced',)),
    CompanySource("ireader", "掌阅科技", "feishu", "q7w8vltyes.jobs.feishu.cn", ('zhangyue',), "https://q7w8vltyes.jobs.feishu.cn/", channels=('experienced',)),
    CompanySource("coconutisland", "椰岛游戏", "feishu", "coconutisland.jobs.feishu.cn", ('coconut_jobs',), "https://coconutisland.jobs.feishu.cn/", channels=('experienced',)),
    CompanySource("soul", "Soul", "feishu", "soulapp.jobs.feishu.cn", ('index',), "https://soulapp.jobs.feishu.cn/index", channels=('experienced',)),
    CompanySource("tuhu", "途虎养车", "moka", "tuhu", ('campus',), "https://app.mokahr.com/campus-recruitment/tuhu/28398", site_id=28398, channels=('campus',)),
    CompanySource("vipshop", "唯品会", "moka", "vipshophr", ('social',), "https://app-tc.mokahr.com/social-recruitment/vipshophr/10038", site_id=10038, channels=('experienced',)),
    CompanySource("weimob", "微盟", "weimob", "job.weimob.com", ("all",), "https://job.weimob.com/public/websitePositionList?t=1", channels=("experienced", "campus", "internship")),
    CompanySource('li', '理想汽车', 'feishu', 'li.jobs.feishu.cn', ('index',), 'https://li.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('zeron', '零一汽车', 'feishu', 'zeron.jobs.feishu.cn', ('campus',), 'https://zeron.jobs.feishu.cn/', channels=('campus',)),
    CompanySource('ecartech', '易咖智车', 'feishu', 'ecartech.jobs.feishu.cn', ('index',), 'https://ecartech.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('ecarx', '亿咖通', 'feishu', 'ecarxgroup.jobs.feishu.cn', ('professional',), 'https://ecarxgroup.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('desaysv', '德赛西威', 'feishu', 'yesv-desaysv.jobs.feishu.cn', ('index',), 'https://yesv-desaysv.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('x2robot', '自变量机器人', 'feishu', 'x2-robot.jobs.feishu.cn', ('index',), 'https://x2-robot.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('agibot', '智元机器人', 'feishu', 'agirobot.jobs.feishu.cn', ('campusrecruitment', 'index'), 'https://agirobot.jobs.feishu.cn/', channels=('experienced', 'campus')),
    CompanySource('robotera', '星动纪元', 'feishu', 'k0fqxcszc9.jobs.feishu.cn', ('index',), 'https://k0fqxcszc9.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('spirit', '千寻智能', 'feishu', 'nwd4iy9rd2s.jobs.feishu.cn', ('index',), 'https://nwd4iy9rd2s.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('tars', '它石智航', 'feishu', 'tarsrobot.jobs.feishu.cn', ('index',), 'https://tarsrobot.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('flexiv', '非夕机器人', 'feishu', 'flexivrobotics.jobs.feishu.cn', ('index',), 'https://flexivrobotics.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('sharpa', 'Sharpa', 'feishu', 'fcn5hvc5qbfs.jobs.feishu.cn', ('668262',), 'https://fcn5hvc5qbfs.jobs.feishu.cn/', channels=('campus',)),
    CompanySource('mammotion', '库犸科技', 'feishu', 'mammotion.jobs.feishu.cn', ('social_recruitment', 'campus_recruitment'), 'https://mammotion.jobs.feishu.cn/', channels=('campus',)),
    CompanySource('ponyai', '小马智行', 'feishu', 'ponyai.jobs.feishu.cn', ('ponyai',), 'https://ponyai.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('holomatic', '禾多科技', 'feishu', 'holomatic.jobs.feishu.cn', ('index',), 'https://holomatic.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('neuehct', '智驾新程', 'feishu', 'neuehct.jobs.feishu.cn', ('index',), 'https://neuehct.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('houmo', '后摩智能', 'feishu', 'houmo.jobs.feishu.cn', ('career',), 'https://houmo.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('brightchip', '光明之芯', 'feishu', 'brightchip.jobs.feishu.cn', ('index',), 'https://brightchip.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('icleague', '芯盟科技', 'feishu', 'icleague.jobs.feishu.cn', ('index',), 'https://icleague.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('carizon', '酷睿程', 'feishu', 'carizon.jobs.feishu.cn', ('index',), 'https://carizon.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('hesai', '禾赛科技', 'feishu', 'kwh0jtf778.jobs.feishu.cn', ('index',), 'https://kwh0jtf778.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('wanji', '万集科技', 'feishu', 'fpq5u8xh3h.jobs.feishu.cn', ('index',), 'https://fpq5u8xh3h.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('anker', '安克创新', 'feishu', 'anker-in.jobs.feishu.cn', ('index', 'campushirecn'), 'https://anker-in.jobs.feishu.cn/', channels=('experienced', 'campus')),
    CompanySource('insta360', '影石Insta360', 'feishu', 'arashivision.jobs.feishu.cn', ('socialENG', 'index', 'campus', 'campusENG'), 'https://arashivision.jobs.feishu.cn/', channels=('experienced', 'campus', 'internship')),
    CompanySource('xtool', 'xTool', 'feishu', 'xtool.jobs.feishu.cn', ('index',), 'https://xtool.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('autel', '道通智能', 'feishu', 'iwpirwbutbu.jobs.feishu.cn', ('index',), 'https://iwpirwbutbu.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('hete', '和而泰', 'feishu', 'salcje7shg.jobs.feishu.cn', ('index',), 'https://salcje7shg.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('kengic', '科捷智能', 'feishu', 'kengic.jobs.feishu.cn', ('index',), 'https://kengic.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('breo', '倍轻松', 'feishu', 'e0cmewvq7v7.jobs.feishu.cn', ('index',), 'https://e0cmewvq7v7.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('biren', '壁仞科技', 'moka', 'biren', ('social',), 'https://app.mokahr.com/social-recruitment/biren/44726', site_id=44726, channels=('experienced', 'campus')),
    CompanySource('tecorigin', '太初', 'moka', 'tecorigin', ('social',), 'https://app.mokahr.com/social-recruitment/tecorigin/47401', site_id=47401, channels=('experienced', 'campus')),
    CompanySource('voyah', '岚图汽车', 'moka', 'voyah', ('social',), 'https://app.mokahr.com/social-recruitment/voyah/146292', site_id=146292, channels=('experienced',)),
    CompanySource('geely', '吉利', 'moka', 'geely', ('social',), 'https://app.mokahr.com/social-recruitment/geely/102042', site_id=102042, channels=('experienced',)),
    CompanySource('joyson', '均胜集团', 'moka', 'joyson', ('social',), 'https://app.mokahr.com/social-recruitment/joyson/94310', site_id=94310, channels=('experienced',)),
    CompanySource('solax', '艾罗能源', 'moka', 'solaxpower', ('social',), 'https://app.mokahr.com/social-recruitment/solaxpower/151400', site_id=151400, channels=('experienced',)),
    CompanySource('trina', '天合光能', 'moka', 'trinasolar', ('social',), 'https://app.mokahr.com/social-recruitment/trinasolar/39871', site_id=39871, channels=('experienced',)),
    CompanySource('sanhua', '三花智控', 'moka', 'zjshc', ('social',), 'https://app.mokahr.com/social-recruitment/zjshc/56208', site_id=56208, channels=('experienced',)),
    CompanySource('synland', '时代新安', 'moka', 'synland', ('social',), 'https://app.mokahr.com/social-recruitment/synland/58041', site_id=58041, channels=('experienced',)),
    CompanySource('smoore', '思摩尔国际', 'moka', 'smoore', ('social',), 'https://app.mokahr.com/social-recruitment/smoore/126055', site_id=126055, channels=('experienced',)),
    CompanySource('zte', '中兴', 'moka', 'zte', ('social',), 'https://app.mokahr.com/social-recruitment/zte/47588', site_id=47588, channels=('experienced', 'campus')),
    CompanySource('dreame', '追觅', 'beisen', 'dreame.zhiye.com', ('1', '2'), 'https://dreame.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('chery', '奇瑞汽车', 'beisen', 'chery.zhiye.com', ('1', '2'), 'https://chery.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('leapmotor', '零跑汽车', 'beisen', 'leapmotor.zhiye.com', ('1', '2'), 'https://leapmotor.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('boe', '京东方', 'beisen', 'boe.zhiye.com', ('1',), 'https://boe.zhiye.com/', channels=('experienced',)),
    CompanySource('sany', '三一集团', 'beisen', 'sany.zhiye.com', ('1', '2'), 'https://sany.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('weichai', '潍柴集团', 'beisen', 'weichai.zhiye.com', ('1', '2'), 'https://weichai.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('dahua', '大华股份', 'beisen', 'dahua.zhiye.com', ('1', '2'), 'https://dahua.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('transsion', '传音', 'beisen', 'transsion.zhiye.com', ('1', '2'), 'https://transsion.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('gotion', '国轩高科', 'beisen', 'gotion.zhiye.com', ('1', '2'), 'https://gotion.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('catl', '宁德时代', 'moka-campus', 'catlhr', ('campus',), 'https://app.mokahr.com/campus-recruitment/catlhr/148948', site_id=148948, channels=('campus',)),
    CompanySource('nio', '蔚来', 'feishu', 'nio.jobs.feishu.cn', ('index', 'campus'), 'https://nio.jobs.feishu.cn/', channels=('experienced', 'campus')),
    CompanySource('xpeng', '小鹏汽车', 'feishu', 'xiaopeng.jobs.feishu.cn', ('index', 'campus'), 'https://xiaopeng.jobs.feishu.cn/', channels=('experienced', 'campus')),
    CompanySource('bambulab', '拓竹科技', 'feishu', 'bambulab.jobs.feishu.cn', ('experienced', 'campus'), 'https://bambulab.jobs.feishu.cn/', channels=('experienced', 'campus')),
    CompanySource('momenta', 'Momenta', 'feishu', 'momenta.jobs.feishu.cn', ('talent',), 'https://momenta.jobs.feishu.cn/', channels=('experienced',)),
    CompanySource('changan', '长安汽车', 'beisen', 'changan.zhiye.com', ('1', '2'), 'https://changan.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('hisense', '海信', 'beisen', 'hisense1.zhiye.com', ('1', '2'), 'https://hisense1.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('h3c', '新华三', 'beisen', 'h3c.zhiye.com', ('1', '2'), 'https://h3c.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('cxmt', '长鑫存储', 'beisen', 'cxmt.zhiye.com', ('1', '2'), 'https://cxmt.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('ymtc', '长江存储', 'beisen', 'ymtc.zhiye.com', ('1', '2'), 'https://ymtc.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('inovance', '汇川技术', 'beisen', 'inovance.zhiye.com', ('1',), 'https://inovance.zhiye.com/', channels=('experienced',)),
    CompanySource('mindray', '迈瑞医疗', 'beisen', 'mindray.zhiye.com', ('1', '2'), 'https://mindray.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('3peak', '思瑞浦', 'moka', '3peakic', ('campus',), 'https://app.mokahr.com/campus-recruitment/3peakic/67894', site_id=67894, channels=('campus',)),
    CompanySource('cambricon', '寒武纪', 'moka', 'cambricon', ('campus',), 'https://app.mokahr.com/campus-recruitment/cambricon/44201', site_id=44201, channels=('campus',)),
    CompanySource('huahong', '华虹集团', 'moka', 'huahong', ('campus',), 'https://app.mokahr.com/campus-recruitment/huahong/70000', site_id=70000, channels=('campus',)),
    CompanySource('qianli', '千里科技', 'moka', 'qianli1', ('campus',), 'https://app.mokahr.com/campus-recruitment/qianli1/147197', site_id=147197, channels=('campus',)),
    CompanySource('ninebot', '九号公司', 'moka', 'ninebot', ('campus',), 'https://app.mokahr.com/campus-recruitment/ninebot/45627', site_id=45627, channels=('campus',)),
    CompanySource('yanfeng', '延锋', 'moka', 'yanfeng', ('campus',), 'https://app.mokahr.com/campus-recruitment/yanfeng/45086', site_id=45086, channels=('campus',)),
    CompanySource('envision', '远景能源', 'moka', 'envisiongroup', ('campus',), 'https://app.mokahr.com/campus-recruitment/envisiongroup/43123', site_id=43123, channels=('campus',)),
    CompanySource('catl-social', '宁德时代', 'moka', 'catlhr', ('social',), 'https://app.mokahr.com/apply/catlhr/96144', site_id=96144, channels=('experienced',)),
    CompanySource('mthreads', '摩尔线程', 'beisen', 'mthreads.zhiye.com', ('1', '2'), 'https://mthreads.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('vivo-campus', 'vivo', 'beisen', 'hr-campus.vivo.com', ('2',), 'https://hr-campus.vivo.com/', channels=('campus',)),
    CompanySource('nexchip', '晶合集成', 'beisen', 'nexchip.zhiye.com', ('1', '2'), 'https://nexchip.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('deye', '德业股份', 'beisen', 'deye.zhiye.com', ('1', '2'), 'https://deye.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('pylontech', '派能科技', 'beisen', 'pylontech1.zhiye.com', ('1', '2'), 'https://pylontech1.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource('tclzhonghuan', 'TCL中环', 'beisen', 'zhonghuan.zhiye.com', ('1', '2'), 'https://zhonghuan.zhiye.com/', channels=('experienced', 'campus')),
    CompanySource("haier", "海尔", "haier", "maker.haier.net", ("all",), "https://maker.haier.net/client/job/index.html"),
    CompanySource("oppo-campus", "OPPO", "oppo-campus", "careers.oppo.com", ("campus",), "https://careers.oppo.com/campus/post", channels=("campus", "internship")),
    CompanySource("byd", "比亚迪", "byd", "job.byd.com", ("social", "应届生", "实习生", "博士生", "外派专项"), "https://job.byd.com/portal/pc/", channels=("experienced", "campus", "internship")),
    CompanySource("midea", "美的集团", "midea", "recruit.midea.com", ("social",), "https://recruit.midea.com/recruitOut/ihr/social", channels=("experienced",)),
    CompanySource("gree", "格力电器", "gree", "zhaopin.greeyun.com", ("1", "2"), "https://zhaopin.greeyun.com/home", channels=("campus", "experienced")),
    CompanySource("hikvision", "海康威视", "hikvision", "talent.hikvision.com", ("social",), "https://talent.hikvision.com/society/index", channels=("experienced", "internship")),
    CompanySource("honor", "荣耀", "dayee", "career.honor.com", ("SU5ff669649b0d78e6f4296c9a:2", "SU60eea919bef57c1023f6fe78:1"), "https://career.honor.com/SU5ff669649b0d78e6f4296c9a/pb/social.html", channels=("experienced", "campus")),
    CompanySource("longi", "隆基绿能", "dayee", "longi.hotjob.cn", ("SU649d2f9c0dcad4644b43df7e:2", "SU649d2f9c0dcad4644b43df7e:1"), "https://longi.hotjob.cn/SU649d2f9c0dcad4644b43df7e/pb/social.html", channels=("experienced", "campus")),
    CompanySource("unitree", "宇树科技", "beisen", "unitree.zhiye.com", ("1", "2", "3"), "https://unitree.zhiye.com/", channels=("experienced", "campus", "internship")),
    CompanySource("roborock", "石头科技", "beisen", "roborock.zhiye.com", ("1", "2", "3"), "https://roborock.zhiye.com/", channels=("experienced", "campus", "internship")),
    CompanySource("xcmg-social", "徐工", "moka", "xcmg", ("social",), "https://app.mokahr.com/social-recruitment/xcmg/148090", site_id=148090, channels=("experienced",)),
    CompanySource("xcmg-campus", "徐工", "moka-campus", "xcmg", ("campus",), "https://app.mokahr.com/campus-recruitment/xcmg/148091", site_id=148091, channels=("campus",)),
)


def validate_source(adapter_key: str, config: dict) -> str:
    try:
        value = SourceConfig.model_validate(config)
    except ValueError as error:
        raise ApiError(400, "JOB_SOURCE_INVALID") from error
    for source in CATALOG:
        if (adapter_key == source.adapter and value.host == source.host
                and len(set(value.portals)) == len(value.portals) and set(value.portals) <= set(source.portals) and value.site_id == source.site_id):
            return source.host
    raise ApiError(400, "JOB_SOURCE_INVALID")


def entry_for(adapter: str, tenant: str, config: dict | None = None) -> CompanySource:
    return next(source for source in CATALOG if source.adapter == adapter and source.host == tenant
                and (adapter not in {"moka", "moka-campus"} or config is None or source.site_id == config.get("site_id")))
