using System.ComponentModel;
using System.Text.Json.Nodes;
using LinkResume.Core.Api;
using LinkResume.Core.Models;
using LinkResume.Core.Session;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media;

namespace LinkResume.App.Views;

/// All library controls and document text are native. Files never pass through a WebView.
public sealed class DatasetLibraryPage : Page {
    readonly StackPanel _page=new(){Spacing=24,MaxWidth=924,Padding=new Thickness(32,52,32,40)};
    readonly CancellationTokenSource _life=new();
    List<DatasetRecord> _files=[];
    List<JsonNode> _folders=[];
    JsonNode? _limits;
    readonly HashSet<string> _selected=[];
    readonly Stack<string> _history=new();
    readonly List<Queued> _queue=[];
    string _inspected="";
    string _folder="",_query="",_filter="all",_error="",_notice="";
    bool _loaded,_busy,_pending;
    int _generation;
    ContentDialog? _dialog;
    sealed class Queued(DatasetUpload upload){public DatasetUpload Upload=upload;public string Status="selected",Message="等待上传";}
    static string S(JsonNode? n,string key)=>n?[key]?.GetValue<string>()??"";
    static List<JsonNode> Items(JsonNode? n)=>n?.AsArray().OfType<JsonNode>().ToList()??[];
    static readonly FontFamily LibrarySans=new("ms-appx:///Assets/Library/LibrarySans-Regular.otf#LinkResume Library Sans");
    static readonly FontFamily LibrarySerif=new("ms-appx:///Assets/Library/LibrarySerif-SemiBold.ttf#LinkResume Library Serif");
    static TextBlock T(string s,double size=13,bool muted=false){var text=InterviewSchedulePage.Text(s,size,muted);text.FontFamily=LibrarySans;return text;}
    static StackPanel Stack(params UIElement[] items){var p=new StackPanel{Spacing=12};foreach(var x in items)p.Children.Add(x);return p;}
    static StackPanel Row(params UIElement[] items){var p=Stack(items);p.Orientation=Orientation.Horizontal;return p;}
    static Border Card(UIElement child)=>new(){Child=child,Padding=new Thickness(16),CornerRadius=new CornerRadius(14),Background=new SolidColorBrush(Microsoft.UI.Colors.White),BorderThickness=new Thickness(1),BorderBrush=new SolidColorBrush(Windows.UI.Color.FromArgb(255,228,228,224))};
    Button B(string label,Action action,bool dark=false){var b=InterviewSchedulePage.Button(label,action,dark);b.IsEnabled=!_busy;return b;}
    bool SignedIn=>App.Session.Phase==SessionViewModel.SessionPhase.SignedIn;
    string Title=>_folder==""?"资料库":_folder=="uncategorized"?"未分类":S(_folders.FirstOrDefault(x=>S(x,"id")==_folder),"name");
    long MediaLimit=>Math.Min(512L*1024*1024,_limits?["max_media_file_bytes"]?.GetValue<long>()??500L*1024*1024);
    int Batch=>Math.Max(1,_limits?["max_files_per_batch"]?.GetValue<int>()??10);
    IEnumerable<DatasetRecord> Visible=>_files.Where(x=>(_folder==""||(_folder=="uncategorized"?x.Folder=="":x.Folder==_folder))&&x.Name.Contains(_query,StringComparison.OrdinalIgnoreCase)&&(_filter=="all"||_filter=="ready"&&x.Ready||_filter=="processing"&&x.Busy||_filter=="failed"&&x.Status.Contains("失败")||_filter==x.Text("asset_kind")));
    public DatasetLibraryPage(){Content=new ScrollViewer{Content=_page};Loaded+=async(_,_)=>{App.Session.PropertyChanged+=Changed;Render();await Load(true);};Unloaded+=(_,_)=>{++_generation;_life.Cancel();_dialog?.Hide();App.Session.PropertyChanged-=Changed;ClearQueue();};}
    void ClearQueue(){foreach(var item in _queue)item.Upload.Discard();_queue.Clear();}
    async void Changed(object? sender,PropertyChangedEventArgs e){if(e.PropertyName!=nameof(SessionViewModel.Phase))return;++_generation;_dialog?.Hide();ClearQueue();_files=[];_folders=[];_selected.Clear();_history.Clear();_limits=null;_folder="";_inspected="";_query="";_error="";_notice="";_loaded=false;_busy=false;Render();await Load();if(SignedIn&&_pending){_pending=false;await Rename("create");}_=Load(true);}
    async Task<JsonNode> Request(string path,string method="GET",JsonNode? body=null,Dictionary<string,string>? query=null){var owner=App.Session.User?.Id;try{var result=await App.Session.Api.CareerRequestAsync(path,method,query,body,_life.Token);_life.Token.ThrowIfCancellationRequested();if(!SignedIn||owner!=App.Session.User?.Id)throw new OperationCanceledException();return result;}catch{if(_life.IsCancellationRequested||!SignedIn||owner!=App.Session.User?.Id)throw new OperationCanceledException();throw;}}
    async Task Load(bool poll=false){var generation=++_generation;if(!SignedIn){Render();return;}try{do{var files=Request("/api/datasets");var folders=Request("/api/datasets/folders");await Task.WhenAll(files,folders);if(generation!=_generation)return;_files=Items(files.Result["datasets"]).Select(x=>new DatasetRecord(x)).ToList();_limits=files.Result["limits"];_folders=Items(folders.Result["folders"]);_loaded=true;_selected.IntersectWith(_files.Select(x=>x.Id));if(_folder!=""&&_folder!="uncategorized"&&!_folders.Any(x=>S(x,"id")==_folder)){_folder="";_history.Clear();}Render();if(!poll||!_files.Any(x=>x.Busy))break;await Task.Delay(3000,_life.Token);}while(generation==_generation);}catch(OperationCanceledException){}catch(Exception e){if(generation==_generation){_error=Explain(e);Render();}}}
    void Navigate(string folder){if(_busy)return;_history.Push(_folder);_folder=folder;_inspected="";_query="";_selected.Clear();Render();}
    static SolidColorBrush Ink(byte r,byte g,byte b)=>new(Windows.UI.Color.FromArgb(255,r,g,b));
    void Render(){
        _page.Children.Clear();
        var heading=new Grid{ColumnSpacing=24};heading.ColumnDefinitions.Add(new());heading.ColumnDefinitions.Add(new(){Width=GridLength.Auto});
        var eyebrow=T("DATASETS",11);eyebrow.Foreground=Ink(150,150,143);eyebrow.Height=13;
        var title=T(Title,28);title.FontFamily=LibrarySerif;title.Height=40;title.Margin=new Thickness(0,9,0,0);
        var subtitle=T(_folder==""&&(_files.Count>0||_folders.Count>0)?$"{_files.Count} 份资料 · {_folders.Count} 个文件夹":"把履历、项目记录和参考资料集中在这里，写简历时随时调用。",13);subtitle.Foreground=Ink(85,85,79);subtitle.MinHeight=19;subtitle.Margin=new Thickness(0,6,0,0);
        var labels=new StackPanel();labels.Children.Add(eyebrow);labels.Children.Add(title);labels.Children.Add(subtitle);heading.Children.Add(labels);
        var search=new TextBox{Text=_query,PlaceholderText="搜索资料…",Width=200,Height=32,MinHeight=0,FontSize=12,FontFamily=LibrarySans,Padding=new Thickness(32,5,12,5),CornerRadius=new CornerRadius(8),BorderThickness=new Thickness(0),Background=Ink(244,244,242)};
        var searchBox=new Grid();searchBox.Children.Add(search);searchBox.Children.Add(new Image{Source=new Microsoft.UI.Xaml.Media.Imaging.BitmapImage(new Uri(Path.Combine(AppContext.BaseDirectory,"Assets","Library","icon-search.png"))),Width=13,Height=13,HorizontalAlignment=HorizontalAlignment.Left,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(12,0,0,0),IsHitTestVisible=false});
        var create=B("新建文件夹",()=>_=Rename("create"),true);create.Width=120;create.Height=32;create.MinHeight=0;create.FontSize=12;create.FontFamily=LibrarySans;create.CornerRadius=new CornerRadius(7);create.Padding=new Thickness(0);create.Background=Ink(29,29,27);
        var controls=Row(searchBox,create);controls.Spacing=10;controls.Margin=new Thickness(0,32,0,0);controls.VerticalAlignment=VerticalAlignment.Top;Grid.SetColumn(controls,1);heading.Children.Add(controls);_page.Children.Add(heading);
        // Rebuild only results: typing keeps its native focus and caret.
        var results=new StackPanel{Spacing=24};
        void Results(){results.Children.Clear();var original=_resultTarget;_resultTarget=results;if(SignedIn&&!_loaded)results.Children.Add(Stack(T(_error==""?"正在加载资料与文件夹…":"加载失败，请重新加载。",14,true),B("重新加载",()=>{_error="";_=Load(true);})));else if(_folder=="")Root();else Files();_resultTarget=original;}
        search.TextChanged+=(_,_)=>{_query=search.Text;Results();};
        _page.Children.Add(new Border{Height=1,Background=Ink(236,236,234),Margin=new Thickness(0,-3,0,0)});
        if(_folder!=""){
            var toolbar=Row(B("资料库",()=>Navigate("")),T("/ "+Title,12,true),B("刷新",()=>{_error="";_=Load(true);}));
            if(_history.Count>0)toolbar.Children.Insert(0,B("‹ 返回",()=>{_folder=_history.Pop();_selected.Clear();Render();}));
            if(DatasetRequest.Id(_folder))toolbar.Children.Add(B("上传文件",()=>_=Pick(),true));
            var filter=new ComboBox{Width=140};foreach(var option in new[]{("all","全部"),("document","文档"),("audio","音频"),("video","视频"),("ready","可用"),("processing","处理中"),("failed","失败")}){var item=new ComboBoxItem{Content=option.Item2,Tag=option.Item1};filter.Items.Add(item);if(option.Item1==_filter)filter.SelectedItem=item;}filter.SelectionChanged+=(_,_)=>{if(filter.SelectedItem is ComboBoxItem item){_filter=(string)item.Tag;Results();}};toolbar.Children.Add(filter);_page.Children.Add(toolbar);
        }
        Results();_page.Children.Add(results);
        if(_queue.Count>0)Queue();if(_busy)_page.Children.Add(new ProgressRing{IsActive=true,Width=24,Height=24});if(_error!="")_page.Children.Add(Row(T(_error,12),B("重新加载",()=>{_error="";_=Load(true);})));if(_notice!="")_page.Children.Add(T(_notice,12,true));
    }
    StackPanel? _resultTarget;
    StackPanel ResultTarget=>_resultTarget??_page;
    void EmptyFolders(){
        var stage=new Image{Source=new Microsoft.UI.Xaml.Media.Imaging.BitmapImage(new Uri(Path.Combine(AppContext.BaseDirectory,"Assets","Library","empty-folders.png"))),Stretch=Stretch.Uniform,Margin=new Thickness(7)};
        var title=T("还没有文件夹",18);title.FontFamily=LibrarySerif;title.Foreground=Ink(29,29,27);title.Height=26;title.Margin=new Thickness(31,14,31,0);
        var description=T("建议先新建文件夹分类整理，后续写简历时可以快速检索和引用相关资料。",13);description.Foreground=Ink(85,85,79);description.LineHeight=22;description.MinHeight=22;description.Margin=new Thickness(31,8,31,32);
        var content=new StackPanel();content.Children.Add(stage);content.Children.Add(title);content.Children.Add(description);
        var card=new Border{Child=content,MaxWidth=520,HorizontalAlignment=HorizontalAlignment.Stretch,CornerRadius=new CornerRadius(16),BorderBrush=Ink(228,228,224),BorderThickness=new Thickness(1),Background=Ink(255,255,255),Margin=new Thickness(0,35,0,0)};
        ResultTarget.Children.Add(card);
    }
    Image Illustration(string name,double height)=>new(){Source=new Microsoft.UI.Xaml.Media.Imaging.BitmapImage(new Uri(Path.Combine(AppContext.BaseDirectory,"Assets","Library",name+".png"))),Height=height,Stretch=Stretch.UniformToFill,IsHitTestVisible=false};
    void Root(){
        if(_folders.Count==0&&_files.Count==0){EmptyFolders();return;}
        var label=new Grid();label.Children.Add(T("文件夹",13));var sort=T("按最近更新",11,true);sort.HorizontalAlignment=HorizontalAlignment.Right;label.Children.Add(sort);ResultTarget.Children.Add(label);
        var grid=new Grid{ColumnSpacing=20,RowSpacing=20,Margin=new Thickness(0,-12,0,0)};
        var cards=new List<UIElement>();var folders=_folders.Where(x=>S(x,"name").Contains(_query,StringComparison.OrdinalIgnoreCase)).ToList();
        if(_files.Any(x=>x.Folder==""))folders.Add(new JsonObject{["id"]="uncategorized",["name"]="未分类",["dataset_count"]=_files.Count(x=>x.Folder=="")});
        foreach(var folder in folders){
            var records=_files.Where(x=>x.Folder==(S(folder,"id")=="uncategorized"?"":S(folder,"id"))).ToList();var count=folder["dataset_count"]?.GetValue<int>()??records.Count;
            var art=Illustration(count==0?"folder-empty":count<3?"folder-project":"folder-documents",96);art.Margin=new Thickness(7);
            var name=T(S(folder,"name"),14);name.Margin=new Thickness(17,6,41,0);name.TextWrapping=TextWrapping.NoWrap;name.TextTrimming=TextTrimming.CharacterEllipsis;
            var caption=T(count==0?"空文件夹 · 进入后上传资料":$"{count} 份资料"+(records.FirstOrDefault() is {} latest?" · 最近上传 "+Date(latest.Text("created_at")):""),11,true);caption.Margin=new Thickness(17,4,17,0);caption.TextWrapping=TextWrapping.NoWrap;caption.TextTrimming=TextTrimming.CharacterEllipsis;
            var body=new StackPanel();body.Children.Add(art);body.Children.Add(name);body.Children.Add(caption);
            var open=B("",()=>Navigate(S(folder,"id")));open.Content=body;open.Padding=new Thickness(0);open.HorizontalContentAlignment=HorizontalAlignment.Stretch;open.VerticalContentAlignment=VerticalAlignment.Top;open.Height=172;open.Background=Ink(255,255,255);open.BorderBrush=Ink(228,228,224);open.BorderThickness=new Thickness(1);open.CornerRadius=new CornerRadius(16);
            var card=new Grid();card.Children.Add(open);
            if(DatasetRequest.Id(S(folder,"id"))){var menu=new MenuFlyout();var rename=new MenuFlyoutItem{Text="重命名"};rename.Click+=(_,_)=>_=Rename("folder",folder);var delete=new MenuFlyoutItem{Text="删除文件夹及其中资料…"};delete.Click+=(_,_)=>_=DeleteFolder(folder);menu.Items.Add(rename);menu.Items.Add(delete);var more=B("•••",()=>{});more.Content=Illustration("icon-more",14);more.Flyout=menu;more.MinWidth=0;more.Padding=new Thickness(0);more.Width=24;more.Height=24;more.HorizontalAlignment=HorizontalAlignment.Right;more.VerticalAlignment=VerticalAlignment.Top;more.Margin=new Thickness(0,114,14,0);more.Background=new SolidColorBrush(Microsoft.UI.Colors.Transparent);more.BorderThickness=new Thickness(0);card.Children.Add(more);}
            cards.Add(card);
        }
        var plus=Illustration("icon-plus",16);plus.Width=16;plus.VerticalAlignment=VerticalAlignment.Center;plus.HorizontalAlignment=HorizontalAlignment.Center;var circle=new Border{Child=plus,Width=36,Height=36,CornerRadius=new CornerRadius(18),Background=Ink(244,244,242),HorizontalAlignment=HorizontalAlignment.Center};
        var createLabels=Stack(circle,T("新建文件夹",13),T("按求职用途分类，最多 50 个",11,true));foreach(var child in createLabels.Children.OfType<FrameworkElement>())child.HorizontalAlignment=HorizontalAlignment.Center;
        var create=B("",()=>_=Rename("create"));create.Content=createLabels;create.Height=172;create.CornerRadius=new CornerRadius(16);create.Background=new SolidColorBrush(Microsoft.UI.Colors.Transparent);create.BorderBrush=Ink(196,196,190);create.BorderThickness=new Thickness(1);create.HorizontalContentAlignment=HorizontalAlignment.Stretch;create.BorderThickness=new Thickness(0);
        var createCard=new Grid{Height=172};createCard.Children.Add(create);createCard.Children.Add(new Microsoft.UI.Xaml.Shapes.Rectangle{RadiusX=16,RadiusY=16,Stroke=Ink(196,196,190),StrokeThickness=1,StrokeDashArray=new DoubleCollection{4,3},IsHitTestVisible=false});cards.Add(createCard);
        void Layout(double width){grid.Children.Clear();grid.ColumnDefinitions.Clear();grid.RowDefinitions.Clear();var columns=Math.Max(1,(int)((width+20)/280));for(var i=0;i<columns;i++)grid.ColumnDefinitions.Add(new());for(var i=0;i<(cards.Count+columns-1)/columns;i++)grid.RowDefinitions.Add(new());for(var i=0;i<cards.Count;i++){var element=(FrameworkElement)cards[i];Grid.SetColumn(element,i%columns);Grid.SetRow(element,i/columns);grid.Children.Add(element);}}
        grid.SizeChanged+=(_,e)=>Layout(e.NewSize.Width);Layout(Math.Max(260,_page.ActualWidth-64));ResultTarget.Children.Add(grid);
        var recentLabel=T(_query==""?"最近上传":"搜索结果",13);recentLabel.Margin=new Thickness(0,8,0,0);ResultTarget.Children.Add(recentLabel);
        var recent=new StackPanel();var files=(_query==""?Visible.Take(5):Visible).ToList();
        foreach(var file in files){var row=new Grid{Height=55,ColumnSpacing=12};row.ColumnDefinitions.Add(new(){Width=new GridLength(32)});row.ColumnDefinitions.Add(new());row.ColumnDefinitions.Add(new(){Width=GridLength.Auto});row.ColumnDefinitions.Add(new(){Width=new GridLength(90)});
            var format=T(file.Format,8);format.Foreground=file.Media?Ink(119,99,174):file.Format=="PDF"?Ink(214,69,69):file.Format=="MD"?Ink(59,154,91):Ink(63,111,216);format.HorizontalAlignment=HorizontalAlignment.Center;format.VerticalAlignment=VerticalAlignment.Center;var icon=new Border{Child=format,Width=32,Height=32,CornerRadius=new CornerRadius(8),Background=Ink(244,244,242)};row.Children.Add(icon);
            var open=B(file.Name,()=>{Navigate(file.Folder==""?"uncategorized":file.Folder);_inspected=file.Id;Render();});open.FontSize=13;open.FontFamily=LibrarySans;open.Background=new SolidColorBrush(Microsoft.UI.Colors.Transparent);open.BorderThickness=new Thickness(0);open.Padding=new Thickness(0);open.HorizontalContentAlignment=HorizontalAlignment.Left;Grid.SetColumn(open,1);row.Children.Add(open);
            if(file.Folder!=""){var chip=B(S(_folders.FirstOrDefault(x=>S(x,"id")==file.Folder),"name"),()=>Navigate(file.Folder));chip.Height=22;chip.MinHeight=0;chip.FontSize=11;chip.Padding=new Thickness(8,0,8,0);chip.CornerRadius=new CornerRadius(11);chip.BorderThickness=new Thickness(0);Grid.SetColumn(chip,2);row.Children.Add(chip);}
            var date=T(Date(file.Text("created_at")),11,true);date.HorizontalAlignment=HorizontalAlignment.Right;date.VerticalAlignment=VerticalAlignment.Center;Grid.SetColumn(date,3);row.Children.Add(date);recent.Children.Add(row);if(file.Id!=files.Last().Id)recent.Children.Add(new Border{Height=1,Background=Ink(236,236,234)});
        }
        if(files.Count==0)recent.Children.Add(T("没有匹配的资料。",13,true));var recentCard=Card(recent);recentCard.Padding=new Thickness(18,0,18,0);recentCard.CornerRadius=new CornerRadius(16);recentCard.Margin=new Thickness(0,-12,0,0);ResultTarget.Children.Add(recentCard);
        ResultTarget.Children.Add(T("写简历或和 AI 助手对话时，可以通过「添加资料」选择要引用的文件。",11,true));
    }
    void Files(){var table=new StackPanel{Spacing=16};var all=new CheckBox{Content="全选",IsChecked=Visible.Any()&&Visible.All(x=>_selected.Contains(x.Id)),IsEnabled=!_busy};all.Click+=(_,_)=>{foreach(var item in Visible)if(all.IsChecked==true)_selected.Add(item.Id);else _selected.Remove(item.Id);Render();};table.Children.Add(Row(all,T("名称 · 关联 · 大小 · 上传日期",12,true)));foreach(var item in Visible){var box=new CheckBox{IsChecked=_selected.Contains(item.Id),IsEnabled=!_busy};box.Click+=(_,_)=>{if(box.IsChecked==true)_selected.Add(item.Id);else _selected.Remove(item.Id);Render();};var menu=new MenuFlyout();void Item(string label,Action action,bool enabled=true){var entry=new MenuFlyoutItem{Text=label,IsEnabled=enabled&&!_busy};entry.Click+=(_,_)=>action();menu.Items.Add(entry);}Item("查看 / 下载",()=>_=Open(item),item.Ready);Item("下载原文件",()=>_=Download(item),item.Text("upload_status")=="succeeded");Item("重命名",()=>_=Rename("file",item.Raw));Item("移动到文件夹",()=>{_selected.Clear();_selected.Add(item.Id);_=Move();});Item("管理关联",()=>_=Associate(item));if(item.Retryable)Item("重新解析",()=>_=Act(()=>Request("/api/datasets/"+item.Id+"/retry","POST")));Item("删除…",()=>{_selected.Clear();_selected.Add(item.Id);_=DeleteFiles();},!item.Busy);var more=B("•••",()=>{});more.Flyout=menu;
            var row=new Grid{ColumnSpacing=12};foreach(var w in new[]{40d,-1,150,80,110,40})row.ColumnDefinitions.Add(new(){Width=w<0?new GridLength(1,GridUnitType.Star):new GridLength(w)});UIElement[] parts=[box,Stack(B(item.Format+"  "+item.Name,()=>{_inspected=item.Id;Render();}),T(item.Status,11,true)),B(item.Text("interview_label")==""?"未关联":item.Text("interview_label"),()=>_=Associate(item)),T(item.Size,12,true),T(Date(item.Text("created_at")),12,true),more];for(var i=0;i<parts.Length;i++){Grid.SetColumn((FrameworkElement)parts[i],i);row.Children.Add(parts[i]);}table.Children.Add(Card(row));}
        if(!Visible.Any())table.Children.Add(Card(Stack(T("还没有资料",20),T("上传文档和音视频，集中管理你的个人材料。",13,true))));if(DatasetRequest.Id(_folder)){var drop=Card(Stack(B("拖入文件，或点击上传到「"+Title+"」",()=>_=Pick()),T($"PDF、Word、Markdown、纯文本与音视频 · 每批最多 {Batch} 个文件",11,true)));drop.AllowDrop=true;drop.DragOver+=(_,e)=>{if(!_busy&&SignedIn)e.AcceptedOperation=Windows.ApplicationModel.DataTransfer.DataPackageOperation.Copy;};drop.Drop+=async(_,e)=>{if(_busy||!SignedIn||!e.DataView.Contains(Windows.ApplicationModel.DataTransfer.StandardDataFormats.StorageItems))return;var folder=_folder;var paths=(await e.DataView.GetStorageItemsAsync()).OfType<Windows.Storage.StorageFile>().Select(x=>x.Path).ToArray();await Enqueue(paths,folder);};table.Children.Add(drop);}if(_selected.Count>0)table.Children.Add(Card(Row(T($"已选择 {_selected.Count} 份"),B("移动到文件夹",()=>_=Move()),B("删除所选…",()=>_=DeleteFiles()),B("取消选择",()=>{_selected.Clear();Render();}))));
        var detail=_files.FirstOrDefault(x=>x.Id==_inspected);if(detail is null){ResultTarget.Children.Add(table);return;}var inspector=Card(Stack(Row(T("资料详情",14),B("关闭",()=>{_inspected="";Render();})),T(detail.Format,12,true),T(detail.Name,16),T("状态："+detail.Status+"\n大小："+detail.Size+"\n上传："+Date(detail.Text("created_at"))+"\n关联："+(detail.Text("interview_label")==""?"未关联":detail.Text("interview_label")),12,true),B(detail.Media?"播放音视频":"查看文件",()=>_=Open(detail),true),B("下载原文件",()=>_=Download(detail)),B("重命名",()=>_=Rename("file",detail.Raw)),B("移动到文件夹",()=>{_selected.Clear();_selected.Add(detail.Id);_=Move();}),B("管理关联",()=>_=Associate(detail)),B("删除资料…",()=>{_selected.Clear();_selected.Add(detail.Id);_=DeleteFiles();})));var layout=new Grid{ColumnSpacing=24,RowSpacing=24};layout.Children.Add(table);layout.Children.Add(inspector);void Arrange(double width){layout.ColumnDefinitions.Clear();layout.RowDefinitions.Clear();if(width>=960){layout.ColumnDefinitions.Add(new());layout.ColumnDefinitions.Add(new(){Width=new GridLength(260)});Grid.SetColumn(inspector,1);Grid.SetRow(inspector,0);}else{layout.ColumnDefinitions.Add(new());layout.RowDefinitions.Add(new());layout.RowDefinitions.Add(new());Grid.SetColumn(inspector,0);Grid.SetRow(inspector,1);}}layout.SizeChanged+=(_,e)=>Arrange(e.NewSize.Width);Arrange(_page.ActualWidth-64);ResultTarget.Children.Add(layout);
}
    async Task<bool> Login(){if(SignedIn)return true;_pending=true;await WorkspacePage.Current.RequestLoginAsync(reason:"登录后管理你的资料；游客也可查看资料库界面。");return false;}
    async Task<bool> Dialog(string title,UIElement content,string primary,Func<Task> save){if(_busy||_dialog is not null)return false;var owner=App.Session.User?.Id;_dialog=new(){XamlRoot=XamlRoot,Title=title,Content=content,PrimaryButtonText=primary,CloseButtonText="取消",DefaultButton=ContentDialogButton.Close};var ok=false;_dialog.PrimaryButtonClick+=async(_,e)=>{var def=e.GetDeferral();_busy=true;_dialog.IsPrimaryButtonEnabled=false;_dialog.IsSecondaryButtonEnabled=false;_dialog.IsEnabled=false;try{await save();_life.Token.ThrowIfCancellationRequested();if(owner!=App.Session.User?.Id)throw new OperationCanceledException();ok=true;}catch(OperationCanceledException){e.Cancel=true;}catch(Exception ex){e.Cancel=true;_error=Explain(ex);if(content is StackPanel p){p.Children.Add(T(_error,12));}}finally{_busy=false;if(_dialog is not null){_dialog.IsPrimaryButtonEnabled=true;_dialog.IsEnabled=true;}def.Complete();}};await _dialog.ShowAsync();_dialog=null;if(ok)await Load(true);else Render();return ok;}
    async Task Rename(string kind,JsonNode? item=null){if(!await Login())return;var field=new TextBox{Text=kind=="folder"?S(item,"name"):S(item,"file_name"),PlaceholderText="名称"};await Dialog(kind=="create"?"新建文件夹":kind=="folder"?"重命名文件夹":"重命名资料",Stack(field),"保存",async()=>{var path=kind=="create"?"/api/datasets/folders":kind=="folder"?"/api/datasets/folders/"+S(item,"id"):"/api/datasets/"+S(item,"id");await Request(path,kind=="create"?"POST":"PATCH",new JsonObject{["name"]=field.Text});});}
    ComboBox Folders(){var picker=new ComboBox{PlaceholderText="请选择目标文件夹",HorizontalAlignment=HorizontalAlignment.Stretch};foreach(var folder in _folders)picker.Items.Add(new ComboBoxItem{Content=S(folder,"name"),Tag=S(folder,"id")});return picker;}
    async Task Move(){var ids=_selected.Order().ToArray();var picker=Folders();await Dialog("移动资料",Stack(T($"移动 {ids.Length} 份资料"),picker),"移动",async()=>{if(picker.SelectedItem is not ComboBoxItem item)throw new InvalidDataException();await Request("/api/datasets/move-batch","POST",new JsonObject{["folder_id"]=(string)item.Tag,["dataset_ids"]=new JsonArray(ids.Select(x=>(JsonNode?)JsonValue.Create(x)).ToArray())});_selected.Clear();});}
    async Task DeleteFolder(JsonNode folder)=>await Dialog("删除文件夹？",Stack(T($"永久删除「{S(folder,"name")}」及其中全部 {folder["dataset_count"]} 份资料，无法恢复。正在处理的资料会阻止删除。")),"永久删除",async()=>{await Request("/api/datasets/folders/"+S(folder,"id"),"DELETE",query:new(){{"confirm_contents","true"}});});
    async Task DeleteFiles(){var items=_files.Where(x=>_selected.Contains(x.Id)).ToArray();await Dialog("删除所选资料？",Stack(T("永久删除以下资料及原文件，无法恢复。"),T(string.Join("\n",items.Select(x=>x.Name)))),"永久删除",async()=>{List<string> failed=[];foreach(var item in items){try{await Request("/api/datasets/"+item.Id,"DELETE");_selected.Remove(item.Id);}catch(OperationCanceledException){throw;}catch(Exception e){failed.Add(item.Name+"："+Explain(e));}}await Load();if(failed.Count>0)throw new IOException(string.Join("；",failed));});}
    async Task Associate(DatasetRecord item){if(_busy)return;try{List<JsonNode> sessions=[];var cursor="";var seen=new HashSet<string>();do{var query=new Dictionary<string,string>{{"limit","500"}};if(cursor!="")query["cursor"]=cursor;var result=await Request("/api/interview-sessions",query:query);sessions.AddRange(Items(result["items"]));cursor=S(result,"next_cursor");if(cursor!=""&&!seen.Add(cursor))throw new InvalidDataException();}while(cursor!="");var picker=new ComboBox{PlaceholderText="选择面试场次",HorizontalAlignment=HorizontalAlignment.Stretch};picker.Items.Add(new ComboBoxItem{Content="取消关联",Tag=""});foreach(var s in sessions){var option=new ComboBoxItem{Content=S(s,"company_name")+" · "+S(s,"job_title")+" · "+S(s,"stage_label"),Tag=S(s,"id")};picker.Items.Add(option);if(S(s,"id")==item.Text("interview_session_id"))picker.SelectedItem=option;}var old=item.Text("interview_session_id");await Dialog("管理关联",Stack(T("换场次先解除旧关联；新关联失败时旧关联不会自动恢复。",12,true),picker),"保存",async()=>{if(picker.SelectedItem is not ComboBoxItem choice)throw new InvalidDataException();var next=(string)choice.Tag;if(old!=""&&old!=next){await Request("/api/interview-sessions/"+old+"/assets/"+item.Id,"DELETE");old="";_notice="旧关联已解除";}if(next!=""&&next!=old)await Request("/api/interview-sessions/"+next+"/assets/attach","POST",new JsonObject{["dataset_id"]=item.Id});});}catch(OperationCanceledException){}catch(Exception e){_error=Explain(e);Render();}}
    async Task Open(DatasetRecord item){if(_busy)return;if(!item.Ready){_notice=item.Status+"，暂时无法预览。";Render();return;}if(item.Media){await Media(item);return;}try{var result=await Request("/api/datasets/"+item.Id+"/content");if(_dialog is not null)return;_dialog=new(){XamlRoot=XamlRoot,Title=item.Name,CloseButtonText="关闭",Content=new ScrollViewer{Content=NativeMarkdownView.Render(S(result,"markdown")),MaxHeight=560}};await _dialog.ShowAsync();_dialog=null;}catch(OperationCanceledException){}catch(Exception e){_error=Explain(e);Render();}}
    async Task Media(DatasetRecord item){DatasetFile? file=null;Windows.Media.Playback.MediaPlayer? player=null;var owner=App.Session.User?.Id;try{file=await App.Session.Api.DownloadDatasetAsync(item.Id,MediaLimit,_life.Token);_life.Token.ThrowIfCancellationRequested();if(owner!=App.Session.User?.Id||_dialog is not null)throw new OperationCanceledException();var playable=Path.Combine(file.Directory,"preview."+item.Format.ToLowerInvariant());File.Move(file.File,playable);var source=await Windows.Storage.StorageFile.GetFileFromPathAsync(playable);_life.Token.ThrowIfCancellationRequested();if(owner!=App.Session.User?.Id)throw new OperationCanceledException();player=new(){Source=Windows.Media.Core.MediaSource.CreateFromStorageFile(source)};var element=new MediaPlayerElement{AreTransportControlsEnabled=true,Height=380};element.SetMediaPlayer(player);_dialog=new(){XamlRoot=XamlRoot,Title=item.Name,Content=element,CloseButtonText="关闭"};await _dialog.ShowAsync();_dialog=null;}catch(OperationCanceledException){}catch(Exception e){if(owner==App.Session.User?.Id)_error=Explain(e);Render();}finally{player?.Dispose();file?.Discard();}}
    async Task Download(DatasetRecord item){if(_busy||App.NativeWindow is not {} window)return;var picker=new Windows.Storage.Pickers.FileSavePicker{SuggestedFileName=Path.GetFileNameWithoutExtension(item.Name)};picker.FileTypeChoices.Add(item.Format,new List<string>{Path.GetExtension(item.Name)});WinRT.Interop.InitializeWithWindow.Initialize(picker,WinRT.Interop.WindowNative.GetWindowHandle(window));var destination=await picker.PickSaveFileAsync();if(destination is null)return;var owner=App.Session.User?.Id;await Act(async()=>{var file=await App.Session.Api.DownloadDatasetAsync(item.Id,MediaLimit,_life.Token);try{if(owner!=App.Session.User?.Id)throw new OperationCanceledException();File.Copy(file.File,destination.Path,true);_notice="已保存「"+item.Name+"」";}finally{file.Discard();}});}
    IEnumerable<string> Extensions=>Items(_limits?["allowed_extensions"]).Concat(Items(_limits?["media_allowed_extensions"])).Select(x=>x.GetValue<string>().TrimStart('.'));
    async Task Pick(){if(_busy||!DatasetRequest.Id(_folder)||!await Login()||App.NativeWindow is not {} window)return;var picker=new Windows.Storage.Pickers.FileOpenPicker();var extensions=Extensions.ToArray();foreach(var extension in extensions.Length>0?extensions:new[]{"pdf","docx","md","txt","webm","m4a","mp3","wav","ogg","mp4","mov"})picker.FileTypeFilter.Add("."+extension);WinRT.Interop.InitializeWithWindow.Initialize(picker,WinRT.Interop.WindowNative.GetWindowHandle(window));var folder=_folder;var owner=App.Session.User?.Id;var chosen=await picker.PickMultipleFilesAsync();if(owner==App.Session.User?.Id)await Enqueue(chosen.Select(x=>x.Path),folder);}
    async Task Enqueue(IEnumerable<string> paths,string folder){var owner=App.Session.User?.Id;foreach(var path in paths.Take(Math.Max(0,Batch-_queue.Count(x=>x.Status!="accepted")))){try{var media=new[]{"webm","m4a","mp3","wav","ogg","mp4","mov"}.Contains(Path.GetExtension(path).TrimStart('.').ToLowerInvariant());var limit=media?MediaLimit:Math.Min(MediaLimit,_limits?["max_file_bytes"]?.GetValue<long>()??20L*1024*1024);var upload=await Task.Run(()=>DatasetUpload.Snapshot(path,folder,limit));if(_life.IsCancellationRequested||owner!=App.Session.User?.Id||_queue.Count(x=>x.Status!="accepted")>=Batch){upload.Discard();return;}_queue.Add(new(upload));}catch(Exception e){if(!_life.IsCancellationRequested&&owner==App.Session.User?.Id)_error=Explain(e);}}Render();}
    void Queue(){var content=Stack(T("上传队列",17),B("上传 / 重试",()=>_=Upload(),true));foreach(var item in _queue){var controls=Row(T(item.Upload.Name),T(item.Message,12,true));if(item.Status=="conflict"){controls.Children.Add(B("保留两份",()=>_=KeepBoth(item)));var existing=_files.FirstOrDefault(x=>x.Folder==item.Upload.Folder&&x.Name.Normalize()==item.Upload.Name.Normalize()&&!x.Media);if(existing is not null)controls.Children.Add(B("替换…",()=>_=Replace(item,existing)));}if(item.Status!="uploading")controls.Children.Add(B(item.Status=="accepted"?"关闭":"移出",()=>{item.Upload.Discard();_queue.Remove(item);Render();}));content.Children.Add(controls);}content.Children.Add(T("结果不确定时沿用原标识重试；退出账号或离开资料库清理临时文件。",11,true));_page.Children.Add(Card(content));}
    async Task KeepBoth(Queued item){var field=new TextBox{Text=item.Upload.Name};await Dialog("保留两份",Stack(T("请为新文件设置不同名称"),field),"保存",()=>{var ext=Path.GetExtension(item.Upload.Name);var name=field.Text.EndsWith(ext,StringComparison.OrdinalIgnoreCase)?field.Text:field.Text+ext;item.Upload=item.Upload with{Id=Guid.NewGuid().ToString("D"),Name=name};item.Status="selected";item.Message="等待重新上传";return Task.CompletedTask;});}
    async Task Replace(Queued item,DatasetRecord existing)=>await Dialog("替换现有文档？",Stack(T("确认替换「"+existing.Name+"」？旧原文件和解析结果永久删除，无法恢复；保留资料 ID、文件夹和面试关联。")),"确认替换",()=>{item.Upload=item.Upload with{Id=Guid.NewGuid().ToString("D"),Replacing=existing.Id,Revision=existing.Text("content_revision"),Name=existing.Name};item.Status="selected";item.Message="已确认替换，等待上传";return Task.CompletedTask;});
    async Task Upload(){if(_busy)return;await Act(async()=>{var owner=App.Session.User?.Id;foreach(var item in _queue.Where(x=>x.Status is "selected" or "unknown" or "rejected").ToArray()){_life.Token.ThrowIfCancellationRequested();item.Status="uploading";item.Message="正在上传…";Render();try{await App.Session.Api.UploadDatasetAsync(item.Upload,_life.Token);if(owner!=App.Session.User?.Id)throw new OperationCanceledException();item.Status="accepted";item.Message="服务器已接受";item.Upload.Discard();}catch(OperationCanceledException){throw;}catch(Exception e){if(owner!=App.Session.User?.Id)throw new OperationCanceledException();if(e is ApiException api&&(int)api.Status is >=400 and <500){item.Status=api.Code.Contains("CONFLICT")?"conflict":"rejected";item.Upload=item.Upload with{Id=Guid.NewGuid().ToString("D")};item.Message=Explain(e);}else{item.Status="unknown";item.Message="结果尚未确认；重试沿用原标识。";}}}});await Load(true);}
    async Task Act(Func<Task> work){if(_busy||!SignedIn)return;var owner=App.Session.User?.Id;_busy=true;_error="";Render();try{await work();}catch(OperationCanceledException){}catch(Exception e){if(owner==App.Session.User?.Id)_error=Explain(e);}finally{if(owner==App.Session.User?.Id&&!_life.IsCancellationRequested){_busy=false;Render();}}await Load(true);}
    static string Date(string s)=>DateTimeOffset.TryParse(s,out var d)?d.ToLocalTime().ToString("yyyy-MM-dd"):"—";
    static string Explain(Exception e)=>e is ApiException a?a.Code switch{"DATASET_NAME_CONFLICT"=>"同一文件夹已有同名文件，请保留两份或确认替换。","DATASET_CONTENT_CONFLICT"=>"资料已更新，请刷新后重新确认替换。","DATASET_BUSY"=>"资料正在处理，暂时不能删除或替换。","FOLDER_NAME_DUPLICATE"=>"文件夹名称已存在。","FOLDER_NAME_CONFLICT"=>"文件夹名称已存在。","DATASET_IN_PROGRESS"=>"资料正在处理，暂时不能删除或替换。","DATASET_FILE_TOO_LARGE"=>"文件超出上传限制。",_=>$"操作未完成（{a.Code}），请刷新确认状态。"}:e is IOException?"文件操作失败，请确认权限或连接后刷新。":"连接失败，结果尚未确认，请沿用原标识重试。";
}
