using System.ComponentModel;
using System.Text.Json.Nodes;
using LinkResume.Core.Models;
using LinkResume.Core.Session;
using LinkResume.Core.Api;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media;

namespace LinkResume.App.Views;

/// Native text interviews; the server owns questions, scoring and durable progress.
public sealed class MockInterviewPage : Page {
    readonly StackPanel _page=new(){Spacing=24,MaxWidth=1200,Padding=new Thickness(32,52,32,40)};
    readonly CancellationTokenSource _life=new();
    readonly TextBlock _error=InterviewSchedulePage.Text("",12);
    List<MockInterview> _records=[]; List<CareerApplication> _jobs=[]; List<JsonNode> _resumes=[],_materials=[];
    List<ScheduledInterview> _dates=[];
    MockInterview? _detail;
    List<JsonNode> _radar=[];
    string _screen="home",_resume="",_job="__none",_jd="",_type="comprehensive",_difficulty="intermediate",_language="zh",_draft="",_query="",_filter="all";
    int _count=5,_generation;
    bool _loaded, _follow=true,_useMaterials,_busy,_pending,_createUnknown;
    HashSet<string> _chosen=[];
    (string Command,JsonNode Body)? _uncertain;
    ContentDialog? _dialog;
    static TextBlock T(string value,double size=13,bool muted=false)=>InterviewSchedulePage.Text(value,size,muted);
    Button B(string title,Action action,bool dark=false){var button=InterviewSchedulePage.Button(title,action,dark);button.IsEnabled=!_busy;return button;}
    static StackPanel Stack(params UIElement[] items){var s=new StackPanel{Spacing=14};foreach(var item in items)s.Children.Add(item);return s;}
    static StackPanel Row(params UIElement[] items){var s=Stack(items);s.Orientation=Orientation.Horizontal;return s;}
    static Border Card(UIElement content)=>new(){Child=content,Padding=new Thickness(24),CornerRadius=new CornerRadius(14),BorderThickness=new Thickness(1),BorderBrush=new SolidColorBrush(Windows.UI.Color.FromArgb(255,228,228,224)),Background=new SolidColorBrush(Microsoft.UI.Colors.White)};
    static string S(JsonNode? node,string key)=>node?[key]?.GetValue<string>()??"";
    static double N(JsonNode? node,string key)=>node?[key]?.GetValue<double>()??0;
    static string Date(string value)=>DateTimeOffset.TryParse(value,out var date)?date.ToLocalTime().ToString("M月d日 HH:mm"):"—";
    static IEnumerable<JsonNode> Items(JsonNode? node)=>node?.AsArray().Where(x=>x is not null).Select(x=>x!)??Enumerable.Empty<JsonNode>();
    bool SignedIn=>App.Session.Phase==SessionViewModel.SessionPhase.SignedIn;
    public MockInterviewPage(){Content=new ScrollViewer{Content=_page};Loaded+=async(_,_)=>{App.Session.PropertyChanged+=SessionChanged;Render();await Load();};Unloaded+=(_,_)=>{++_generation;_life.Cancel();_dialog?.Hide();App.Session.PropertyChanged-=SessionChanged;};}
    async void SessionChanged(object? sender,PropertyChangedEventArgs args){if(args.PropertyName!=nameof(SessionViewModel.Phase))return;++_generation;_busy=false;_loaded=false;_records=[];_radar=[];_jobs=[];_resumes=[];_materials=[];_dates=[];_detail=null;_draft="";_uncertain=null;_chosen=[];_resume="";_job="__none";_jd="";_query="";_filter="all";_createUnknown=false;_dialog?.Hide();_screen=SignedIn&&_pending?"new":"home";_pending=false;Render();await Load();}
    async Task<JsonNode> Request(string path,string method="GET",JsonNode? body=null,Dictionary<string,string>? query=null){var owner=App.Session.User?.Id;var result=await App.Session.Api.CareerRequestAsync(path,method,query,body,_life.Token);_life.Token.ThrowIfCancellationRequested();if(!SignedIn||owner!=App.Session.User?.Id)throw new OperationCanceledException();return result;}
    async Task<List<JsonNode>> Pages(string path,Dictionary<string,string> query){List<JsonNode> values=[];HashSet<string> seen=[];string cursor="";do{if(cursor!="")query["cursor"]=cursor;var result=await Request(path,query:query);values.AddRange(Items(result["items"]));cursor=S(result,"next_cursor");if(cursor!=""&&!seen.Add(cursor))throw new InvalidDataException();}while(cursor!="");return values;}
    async Task Load(){var generation=++_generation;_error.Text="";if(!SignedIn){Render();return;}try{
        if(_screen=="detail"&&_detail is {} old){do{var data=await Request("/api/mock-interviews/"+old.Id);if(generation!=_generation)return;_detail=new(data["mock_interview"]!);Render();if(_detail.Status is not ("preparing" or "evaluating"))break;await Task.Delay(2000,_life.Token);}while(generation==_generation);return;}
        var records=await Pages("/api/mock-interviews",new(){{"limit","100"}});if(generation!=_generation)return;_records=records.Select(x=>new MockInterview(x)).ToList();_loaded=true;
        var scores=new Dictionary<string,List<double>>();foreach(var item in _records.Where(x=>x.Status=="completed").Take(4)){try{var result=await Request("/api/mock-interviews/"+item.Id);if(generation!=_generation)return;foreach(var dimension in Items(result["mock_interview"]?["report"]?["dimensions"])){var key=S(dimension,"key");if(!scores.ContainsKey(key))scores[key]=[];scores[key].Add(N(dimension,"score"));}}catch(OperationCanceledException){throw;}catch{}}
        _radar=scores.OrderBy(x=>x.Key).Select(x=>(JsonNode)new JsonObject{["key"]=x.Key,["score"]=x.Value.Average()}).ToList();
        try{var jobs=await Pages("/api/job-applications",new(){{"scope","active"},{"limit","200"}});var dates=await Pages("/api/interview-sessions",new(){{"limit","500"}});if(generation!=_generation)return;_jobs=jobs.Select(x=>new CareerApplication(x)).Where(x=>!x.Ended).ToList();_dates=dates.Select(x=>new ScheduledInterview(x)).ToList();}catch(OperationCanceledException){throw;}catch{_error.Text="岗位或排期暂不可用，可以从简历开始练习。";}
        if(_screen=="new"){var data=await Request("/api/resumes");if(generation!=_generation)return;_resumes=Items(data["resumes"]).ToList();if(!_resumes.Any(x=>S(x,"id")==_resume))_resume=_resumes.FirstOrDefault()?["id"]?.GetValue<string>()??"";
            try{var assets=await Request("/api/datasets");if(generation!=_generation)return;_materials=Items(assets["datasets"]).Where(x=>S(x,"asset_kind")=="document"&&S(x,"upload_status")=="succeeded"&&S(x,"parse_status")=="succeeded").ToList();}catch(OperationCanceledException){throw;}catch{_materials=[];_error.Text="参考资料加载失败，可不关联资料继续。";}}
        if(generation==_generation)Render();
    }catch(OperationCanceledException){}catch(Exception e){if(generation==_generation){_error.Text=Explain(e);Render();}}}
    async Task Start(string? job=null){_job=job??"__none";_createUnknown=false;if(!SignedIn){_pending=true;await WorkspacePage.Current.RequestLoginAsync(reason:"登录后开始模拟面试。");return;}_screen="new";Render();await Load();}
    void Open(MockInterview item){_detail=item;_draft="";_uncertain=null;_screen="detail";Render();_=Load();}
    void Back(){if(_busy)return;_screen="home";_detail=null;_draft="";_uncertain=null;Render();_=Load();}
    void Header(string title,string subtitle,bool back=true){if(back)_page.Children.Add(B("‹ 模拟面试",Back));else _page.Children.Add(T("MOCK INTERVIEW · AI 练习",11,true));var heading=T(title,28);heading.FontFamily=new FontFamily("SimSun");heading.FontWeight=Microsoft.UI.Text.FontWeights.SemiBold;_page.Children.Add(heading);_page.Children.Add(T(subtitle,13,true));}
    void Render(){_page.Children.Clear();if(_screen=="home")Home();else if(_screen=="records")Records();else if(_screen=="new")Configuration();else if(_detail is {} item)Detail(item);if(_busy)_page.Children.Add(new ProgressRing{IsActive=true,Width=24,Height=24});_page.Children.Add(_error);_page.Children.Add(B("刷新",()=>_=Load()));}
    void Home(){Header("模拟面试","从一个在投岗位开始，AI 会按岗位 JD 和你的简历出题。",false);_page.Children.Add(Row(B($"练习记录  {(SignedIn&&!_loaded?"—":_records.Count.ToString())}",()=>{_screen="records";Render();_=Load();}),B("开始新面试",()=>_=Start(),true)));
        var next=_dates.Where(x=>x.Editable&&x.Start>=DateTimeOffset.Now).OrderBy(x=>x.Start).FirstOrDefault();
        if(next is not null)_page.Children.Add(Card(Row(Stack(T(Date(next.Text("start_at")),18),T(next.Company+" · "+next.Title,18),T(next.Label,12,true)),B("针对这场练一次",()=>_=Start(next.ApplicationId),true))));
        else if(_records.Count==0&&(!SignedIn||_loaded))_page.Children.Add(Card(Row(Stack(T("还没有面试安排，也还没练过",18),T("选一个在投岗位做第一场练习；添加面试时间后，最近的一场会出现在这里。",13,true),T("① 选岗位    ② 答 5 道题 · 约 25 分钟    ③ 拿到评估报告",12)),B("添加面试时间",()=>WorkspacePage.Current.Navigate(WorkspaceSection.Schedule)))));
        if(_records.FirstOrDefault(x=>x.Active) is {} active)_page.Children.Add(Card(Row(T(active.Title+" · "+active.Label),B("继续本场",()=>Open(active),true))));
        var done=_records.Where(x=>x.Status=="completed").ToList();var stats=new Grid{ColumnSpacing=30};for(var i=0;i<3;i++)stats.ColumnDefinitions.Add(new());
        UIElement[] parts=[Stack(T("综合表现",14),T(done.Count==0?"—":done.Average(x=>N(x.Raw,"total_score")).ToString("F1"),38),T(SignedIn&&!_loaded?"数据暂不可用":$"{done.Count} 场已完成",12,true)),Stack(T("得分趋势",14),T(done.Count==0?"—":string.Join(" → ",done.AsEnumerable().Reverse().TakeLast(4).Select(x=>N(x.Raw,"total_score").ToString("F0"))),24),T("最近四场真实得分",12,true)),Stack(T("能力雷达",14),Radar(_radar),T(_radar.Count==0?"完成练习后查看薄弱项":"最近四场可用报告的维度均分",12,true))];for(var i=0;i<3;i++){Grid.SetColumn((FrameworkElement)parts[i],i);stats.Children.Add(parts[i]);}_page.Children.Add(Card(stats));
        _page.Children.Add(T("从在投岗位开始",17));if(_jobs.Count==0)_page.Children.Add(T(SignedIn?"暂无在投岗位，也可以直接从简历开始。":"登录后查看在投岗位；也可以从简历开始练习。",13,true));foreach(var job in _jobs){var completed=done.Where(x=>S(x.Raw,"job_application_id")==job.Id).ToList();_page.Children.Add(Card(Row(Stack(T(job.Company+" · "+job.Title),T(job.StageLabel+" · "+(completed.Count==0?"未练习":$"{completed.Count} 场 · 最高 {completed.Max(x=>N(x.Raw,"total_score")):F0} 分"),12,true)),B("开始练习",()=>_=Start(job.Id)))));}}
    void Records(){Header("练习记录","每场练习的状态、作答与评估报告");var search=new TextBox{PlaceholderText="搜索公司、岗位或简历",Text=_query,Width=280};var filter=Select("状态",new[]{("all","全部")}.Concat(MockInterview.StatusLabels.Select(x=>(x.Key,x.Value))),_filter,value=>{_filter=value;Render();});search.TextChanged+=(_,_)=>{_query=search.Text;};_page.Children.Add(Row(search,filter,B("查询",Render),B("开始新面试",()=>_=Start(),true)));if(_records.Count==0)_page.Children.Add(T(SignedIn?(_loaded?"还没有练习记录。":"练习记录暂不可用，请重新加载。") :"登录后查看你的练习记录。",13,true));foreach(var item in _records.Where(x=>(_filter=="all"||x.Status==_filter)&&x.Title.Contains(_query,StringComparison.OrdinalIgnoreCase)))_page.Children.Add(B($"{item.Title}    {item.Type}    {item.Label}    {(item.Raw["total_score"] is null?"—":N(item.Raw,"total_score").ToString("F1"))}    {Date(item.Text("created_at"))}",()=>Open(item)));}
    static ComboBox Select(string title,IEnumerable<(string Id,string Label)> values,string selected,Action<string> changed){var picker=new ComboBox{Header=title,MinWidth=180,HorizontalAlignment=HorizontalAlignment.Stretch};foreach(var value in values){var option=new ComboBoxItem{Content=value.Label,Tag=value.Id};picker.Items.Add(option);if(value.Id==selected)picker.SelectedItem=option;}picker.SelectionChanged+=(_,_)=>{if(picker.SelectedItem is ComboBoxItem option)changed((string)option.Tag);};return picker;}
    static CheckBox Toggle(string title,bool value,Action<bool> changed){var box=new CheckBox{Content=title,IsChecked=value};box.Click+=(_,_)=>changed(box.IsChecked==true);return box;}
    void Configuration(){Header("开始新面试","选择简历和目标岗位，AI 会结合你的经历制定考察计划。");var form=Stack(T("面试背景",17),Select("简历",new[]{("","请选择本人简历")}.Concat(_resumes.Select(x=>(S(x,"id"),S(x,"title")))),_resume,x=>_resume=x),Select("目标岗位",new[]{("__none","不指定岗位"),("__jd","粘贴一段 JD")}.Concat(_jobs.Select(x=>(x.Id,x.Company+" · "+x.Title))),_job,x=>{_job=x;if(_jobs.FirstOrDefault(j=>j.Id==x) is {} job){var id=job.Text("resume_id");if(_resumes.Any(r=>S(r,"id")==id))_resume=id;_type=job.StageLabel.StartsWith("HR",StringComparison.OrdinalIgnoreCase)?"hr":"comprehensive";}Render();}));
        if(_resumes.Count==0)form.Children.Add(T("账号中还没有可用简历，请先在 Web 创建或导入后刷新。",12,true));if(_job=="__jd"){var jd=new TextBox{Text=_jd,AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,Height=140,PlaceholderText="粘贴岗位描述",MaxLength=20000};jd.TextChanged+=(_,_)=>_jd=jd.Text;form.Children.Add(jd);}
        form.Children.Add(T("练习设置",17));form.Children.Add(Select("面试类型",MockInterview.Types.Select(x=>(x.Key,x.Value)),_type,x=>_type=x));form.Children.Add(Select("难度",new[]{("junior","初级"),("intermediate","中级"),("senior","高级")},_difficulty,x=>_difficulty=x));var count=new NumberBox{Header="主问题数",Minimum=3,Maximum=10,Value=_count,SpinButtonPlacementMode=NumberBoxSpinButtonPlacementMode.Inline};count.ValueChanged+=(_,_)=>{if(double.IsFinite(count.Value))_count=Math.Clamp((int)count.Value,3,10);};form.Children.Add(count);form.Children.Add(Toggle("允许追问",_follow,x=>_follow=x));form.Children.Add(Select("语言",new[]{("zh","中文"),("en","英文")},_language,x=>_language=x));form.Children.Add(T("文字面试 · 本次通过输入框作答",12,true));form.Children.Add(T("参考资料（可选，最多 10 份）",17));foreach(var material in _materials){var id=S(material,"id");var box=Toggle(S(material,"file_name"),_chosen.Contains(id),value=>{if(value){if(_chosen.Count<10)_chosen.Add(id);}else _chosen.Remove(id);Render();});box.IsEnabled=_chosen.Count<10||_chosen.Contains(id);form.Children.Add(box);}form.Children.Add(Toggle("出题参考所选资料",_useMaterials,x=>_useMaterials=x));form.Children.Add(T("关闭时仅用于报告事实核验；只有选中的资料会被使用。",12,true));foreach(var field in form.Children.OfType<Control>())field.IsEnabled=!_busy&&!_createUnknown;_page.Children.Add(Card(form));var start=B("开始面试",()=>_=Create(),true);start.IsEnabled=!_busy&&!_createUnknown;_page.Children.Add(start);if(_createUnknown)_page.Children.Add(T("创建结果尚未确认。请返回首页刷新确认，避免重复创建。",13,true));}
    async Task Create(){if(_busy||_createUnknown)return;if(_resume==""||(_job=="__jd"&&string.IsNullOrWhiteSpace(_jd))){_error.Text="请选择简历并填写岗位描述。";return;}var body=new JsonObject{["resume_id"]=_resume,["interview_type"]=_type,["difficulty"]=_difficulty,["question_count"]=_count,["follow_up_enabled"]=_follow,["language"]=_language,["answer_mode"]="text",["material_ids"]=new JsonArray(_chosen.Order().Select(x=>(JsonNode?)JsonValue.Create(x)).ToArray()),["materials_in_questions"]=_useMaterials&&_chosen.Count>0};if(_job=="__jd")body["job_description_text"]=_jd.Trim();else if(_job!="__none")body["job_application_id"]=_job;
        await Act(async()=>{try{var result=await Request("/api/mock-interviews","POST",body);_detail=new(result["mock_interview"]!);_screen="detail";}catch(Exception e){_createUnknown=e is not ApiException api||((int)api.Status>=500&&api.Code is not ("LLM_MODEL_NOT_CONFIGURED" or "AUTH_SERVICE_UNAVAILABLE"));throw;}});if(_screen=="detail")await Load();}
    void Detail(MockInterview item){Header(item.Status=="completed"?"评估报告":"模拟面试",item.Title+" · "+item.Type+" · "+item.Label);
        if(item.Status=="completed")Report(item);else if(item.Status is "preparing" or "evaluating")_page.Children.Add(Card(Stack(new ProgressRing{IsActive=true,Width=30,Height=30},T(item.Status=="preparing"?"AI 正在分析背景并准备问题":"正在生成评估报告",18),T("可以离开页面，稍后从练习记录继续查看。",13,true))));
        else if(item.Status is "preparation_failed" or "evaluation_failed")_page.Children.Add(Card(Stack(T(item.Label,18),T(item.Text("error_code")),B("重试",()=>_=Command("retry"),true))));
        else if(item.Status=="abandoned")_page.Children.Add(T("本场已放弃，未生成报告。",13,true));
        if(item.Status is "in_progress" or "abandoned" or "evaluation_failed")foreach(var q in Items(item.Questions))_page.Children.Add(Card(Stack(T($"{(S(q,"kind")=="follow_up"?"追问":"问题")} {N(q,"sequence_no"):F0} · {S(q,"content")}",16),T(S(q,"answer_status")=="skipped"?"已跳过":S(q,"answer_text"),13,true))));
        if(item.Status=="in_progress"){
            _page.Children.Add(T($"主问题进度 {N(item.Raw,"answered_main_questions"):F0} / {N(item.Raw,"question_count"):F0}",12,true));
            _page.Children.Add(Row(B("结束并生成报告",()=>_=Confirm("finish")),B("放弃本场",()=>_=Confirm("abandon"))));
            if(item.Raw["needs_reply"]?.GetValue<bool>()==true)_page.Children.Add(Card(Stack(T("回答已保存，面试官回复尚未完成。"),B("重新生成回复",()=>_=Command("reply:retry"),true))));
            else if(item.Text("answer_mode")=="voice")_page.Children.Add(T("本场是语音面试，请在 Web 继续作答。",13,true));
            else if(item.Current is {} question){var answer=new TextBox{Text=_draft,AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=140,MaxLength=8000,PlaceholderText="输入你的回答…",IsEnabled=!_busy&&_uncertain is null};answer.TextChanged+=(_,_)=>_draft=answer.Text;var submit=B("提交回答",()=>_=Answer(question,false),true);submit.IsEnabled=!_busy&&_uncertain is null;var skip=B("跳过本题",()=>_=Answer(question,true));skip.IsEnabled=submit.IsEnabled;_page.Children.Add(Card(Stack(answer,Row(skip,submit))));}
            if(_uncertain is {} pending)_page.Children.Add(B("重试原提交",()=>_=SendAnswer(pending.Command,pending.Body)));
        }
        if(item.Status=="preparation_failed")_page.Children.Add(B("放弃本场",()=>_=Confirm("abandon")));
        if(!item.Active){var repeat=B("再练一次",()=>_=Command("repeat"),true);repeat.IsEnabled=!_busy&&item.Text("answer_mode")!="voice"&&!_createUnknown;_page.Children.Add(Row(repeat,B("删除记录",()=>_=Confirm("delete"))));}}
    void Report(MockInterview item){var report=item.Raw["report"];if(report is null){_page.Children.Add(T("报告暂不可用，请刷新重试。"));return;}_page.Children.Add(Card(Stack(T(N(report,"total_score").ToString("F1")+" 分",48),T(S(report,"headline"),18),T(S(report,"summary")),T($"逐题平均 {N(report,"question_average"):F1} · 维度得分 {N(report,"dimension_score"):F1}",13,true),T(report["low_confidence"]?.GetValue<bool>()==true?"作答样本较少，报告置信度较低":"",12,true))));var dimensions=Stack(T("能力维度",17),Radar(Items(report["dimensions"]).ToList()));foreach(var dimension in Items(report["dimensions"]))dimensions.Children.Add(Stack(Row(T(MockInterview.Dimensions.GetValueOrDefault(S(dimension,"key"),S(dimension,"key"))),new ProgressBar{Value=N(dimension,"score"),Maximum=5,Width=160},T(N(dimension,"score").ToString("F1"))),T(S(dimension,"comment"),12,true),T("依据："+string.Join("；",Items(dimension["evidence"]).Select(x=>x.GetValue<string>())),12,true)));_page.Children.Add(Card(dimensions));
        foreach(var evaluation in Items(report["questions"])){var content=Stack();var main=Items(item.Questions).FirstOrDefault(q=>S(q,"kind")=="main"&&N(q,"sequence_no")==N(evaluation,"sequence_no"));foreach(var q in Items(item.Questions).Where(q=>main is not null&&N(q,"plan_index")==N(main,"plan_index")))content.Children.Add(Stack(T("问："+S(q,"content")),T("答："+(S(q,"answer_status")=="skipped"?"已跳过":S(q,"answer_text")),13,true)));foreach(var signal in Items(evaluation["signals"]))content.Children.Add(T(S(signal,"signal")+" · "+new Dictionary<string,string>{{"hit","命中"},{"partial","部分命中"},{"miss","未命中"}}.GetValueOrDefault(S(signal,"verdict"),S(signal,"verdict"))+" · "+S(signal,"evidence"),12,true));content.Children.Add(T("参考回答："+S(evaluation,"reference_answer")));Strings(content,evaluation["highlights"],"亮点");Strings(content,evaluation["weaknesses"],"待加强");Strings(content,evaluation["factual_errors"],"事实问题");_page.Children.Add(new Expander{Header=$"{S(evaluation,"topic")} · {N(evaluation,"score"):F0} 分",Content=content,HorizontalAlignment=HorizontalAlignment.Stretch});}
        var facts=Stack(T("参考资料事实核验",17),T(new Dictionary<string,string>{{"not_requested","未选择参考资料"},{"completed","核验已完成"},{"failed","资料核验失败，其他评分仍可查看"}}.GetValueOrDefault(S(report["fact_check"],"status"),"")));foreach(var fact in Items(report["fact_check"]?["items"]))facts.Children.Add(Stack(T(S(fact,"claim")+" · "+new Dictionary<string,string>{{"consistent","有资料支持"},{"conflict","与资料矛盾"},{"not_found","未找到依据"},{"stronger_in_material","资料表述更强"}}.GetValueOrDefault(S(fact,"verdict"),S(fact,"verdict"))),T(S(fact,"note"),12,true),T(S(fact["source"],"title")+"："+S(fact,"quote"),12,true)));Strings(facts,report["resume_risks"],"简历风险");Strings(facts,report["improvements"],"改进建议");_page.Children.Add(Card(facts));}
    static UIElement Radar(List<JsonNode> dimensions){
        var canvas=new Canvas{Width=170,Height=105};var count=dimensions.Count==0?5:Math.Max(3,dimensions.Count);
        Windows.Foundation.Point Point(int i,double scale){var angle=i*2*Math.PI/count-Math.PI/2;return new(85+Math.Cos(angle)*45*scale,52+Math.Sin(angle)*45*scale);}
        foreach(var scale in new[]{0.4,0.7,1.0}){var polygon=new Microsoft.UI.Xaml.Shapes.Polygon{Stroke=new SolidColorBrush(Windows.UI.Color.FromArgb(255,222,222,216)),StrokeThickness=1};for(var i=0;i<count;i++)polygon.Points.Add(Point(i,scale));canvas.Children.Add(polygon);}
        if(dimensions.Count>0){var polygon=new Microsoft.UI.Xaml.Shapes.Polygon{Stroke=new SolidColorBrush(Windows.UI.Color.FromArgb(255,57,118,207)),StrokeThickness=1.5,Fill=new SolidColorBrush(Windows.UI.Color.FromArgb(40,57,118,207))};for(var i=0;i<dimensions.Count;i++)polygon.Points.Add(Point(i,Math.Clamp(N(dimensions[i],"score"),0,5)/5));canvas.Children.Add(polygon);}return canvas;
    }
    static void Strings(StackPanel target,JsonNode? values,string title){var entries=Items(values).ToList();if(entries.Count==0)return;target.Children.Add(T(title,14));foreach(var item in entries)target.Children.Add(T(item.GetValue<string>(),12));}
    async Task Answer(JsonNode question,bool skip){if(_busy||_uncertain is not null)return;if(!skip&&string.IsNullOrWhiteSpace(_draft)){_error.Text="请先输入回答。";return;}var body=new JsonObject{["question_id"]=S(question,"id"),["__idempotency_key"]=Guid.NewGuid().ToString("D")};if(!skip)body["answer"]=_draft.Trim();await SendAnswer(skip?"skip":"answers",body);}
    async Task SendAnswer(string command,JsonNode body){if(_detail is null)return;var id=_detail.Id;_uncertain=(command,body);await Act(async()=>{try{await Request("/api/mock-interviews/"+id+"/"+command,"POST",body);}catch(Exception e){_error.Text=Explain(e);if(e is ApiException api&&(int)api.Status is 400 or 422)_uncertain=null;}var result=await Request("/api/mock-interviews/"+id);_detail=new(result["mock_interview"]!);if(Items(_detail.Questions).Any(q=>S(q,"id")==S(body,"question_id")&&S(q,"answer_status")!="pending")){_uncertain=null;_draft="";}});if(_detail?.Status=="evaluating")await Load();}
    async Task Confirm(string command){if(_busy)return;_dialog=new ContentDialog{XamlRoot=XamlRoot,Title=command=="delete"?"删除练习记录？":command=="finish"?"结束并生成报告？":"放弃本场面试？",Content=command=="delete"?"永久删除本场练习及报告，无法恢复。":command=="finish"?"评估已作答题目；一题未答则放弃本场。":"放弃后不生成报告，作答内容仍保留在记录中。",PrimaryButtonText="确认",CloseButtonText="取消",DefaultButton=ContentDialogButton.Close};if(await _dialog.ShowAsync()==ContentDialogResult.Primary)await Command(command);_dialog=null;}
    async Task Command(string command){if(_detail is null)return;var id=_detail.Id;await Act(async()=>{try{var result=await Request("/api/mock-interviews/"+id+(command=="delete"?"":"/"+command),command=="delete"?"DELETE":"POST");if(command=="delete"){_screen="records";_detail=null;}else if(command!="reply:retry"){_detail=new(result["mock_interview"]!);_draft="";_uncertain=null;}}catch{if(command=="repeat")_createUnknown=true;throw;}});await Load();}
    async Task Act(Func<Task> work){if(_busy||!SignedIn)return;var generation=++_generation;_busy=true;_error.Text="";Render();try{await work();}catch(OperationCanceledException){}catch(Exception e){if(generation==_generation)_error.Text=Explain(e);}finally{if(generation==_generation){_busy=false;Render();}}}
    static string Explain(Exception e)=>e is ApiException api?api.Code switch{"LLM_MODEL_NOT_CONFIGURED"=>"模拟面试模型尚未配置，请配置后重试。","MOCK_INTERVIEW_IN_PROGRESS"=>"已有进行中的面试，请返回首页继续。","MOCK_INTERVIEW_STATE_INVALID"=>"状态已变化，请刷新后再操作。","UNAUTHORIZED"=>"登录已失效，请重新登录。",_=>$"操作未完成（{api.Code}），请刷新确认状态。"}:"连接失败，结果尚未确认。输入已保留，请刷新确认后再试。";
}
