using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Documents;
using System.Text.RegularExpressions;
namespace LinkResume.App.Views;
/// Safe native document preview: no HTML execution, remote images or network links.
internal static class NativeMarkdownView {
    public static UIElement Render(string markdown){var panel=new StackPanel{Spacing=12,MaxWidth=780};var lines=markdown.Replace("\r\n","\n").Split('\n');var code=false;var block=new List<string>();var language="";var count=0;foreach(var raw in lines.Take(5000)){if(++count>5000)break;var line=raw.Length>10000?raw[..10000]:raw;if(line.TrimStart().StartsWith("```")){if(code){var text=new TextBlock{Text=string.Join("\n",block),FontFamily=new FontFamily("Consolas"),IsTextSelectionEnabled=true,TextWrapping=TextWrapping.Wrap};panel.Children.Add(new Border{Child=text,Padding=new Thickness(12),Background=new SolidColorBrush(Windows.UI.Color.FromArgb(255,244,244,241))});if(language=="mermaid")panel.Children.Add(Text("Mermaid 图表源码 · 原生预览暂不执行图表脚本",11));block.Clear();}else language=line.Trim().TrimStart('`').Trim();code=!code;continue;}if(code){block.Add(line);continue;}if(line.TrimStart().StartsWith("![")){panel.Children.Add(Text("文档图片请下载原文件查看",12));continue;}if(line.StartsWith('|')){if(Regex.IsMatch(line,@"^[\s|:\-]+$"))continue;var grid=new Grid{ColumnSpacing=14};var cells=line.Trim().Trim('|').Split('|').Take(20).ToArray();foreach(var _ in cells)grid.ColumnDefinitions.Add(new());for(var i=0;i<cells.Length;i++){var cell=Text(cells[i].Trim(),12);Grid.SetColumn(cell,i);grid.Children.Add(cell);}panel.Children.Add(grid);continue;}var heading=Regex.Match(line,@"^(#{1,6})\s+(.+)$");if(heading.Success){var text=Text(heading.Groups[2].Value,Math.Max(14,25-heading.Groups[1].Length));text.FontWeight=Microsoft.UI.Text.FontWeights.SemiBold;panel.Children.Add(text);continue;}if(string.IsNullOrWhiteSpace(line))continue;var output=Text("",13);var source=Regex.Replace(line,@"^\s*[-*+]\s+","• ");foreach(var chunk in Regex.Split(source,@"(\*\*.*?\*\*|`[^`]+`|\[[^\]]+\]\([^)]+\))")){var run=new Run{Text=chunk};if(chunk.StartsWith("**")&&chunk.EndsWith("**")){run.Text=chunk[2..^2];run.FontWeight=Microsoft.UI.Text.FontWeights.SemiBold;}else if(chunk.StartsWith('`')&&chunk.EndsWith('`')){run.Text=chunk[1..^1];run.FontFamily=new FontFamily("Consolas");}else if(chunk.StartsWith('['))run.Text=Regex.Match(chunk,@"^\[([^\]]+)\]").Groups[1].Value;output.Inlines.Add(run);}panel.Children.Add(output);}if(code&&block.Count>0)panel.Children.Add(Text(string.Join("\n",block),12));if(lines.Length>5000)panel.Children.Add(Text("预览已截断，请下载原文件查看完整内容。",11));return panel;}
    static TextBlock Text(string s,double size)=>new(){Text=s,FontSize=size,TextWrapping=TextWrapping.Wrap,IsTextSelectionEnabled=true};
}
