from linkcv.domain.resume.canonical_json import canonical_json_bytes, canonical_sha256
from linkcv.domain.resume.models import (
    CanonicalResumeDocument,
    InlineIcon,
    InlineIconName,
    LayoutPlan,
    RowBlock,
    RowCell,
    ResumePresentation,
    SourceGraph,
    SparseResumeAnnotations,
    TemplateDefinition,
    TemplateAvatar,
    validate_layout_coverage,
    validate_source_closure,
    validate_sparse_annotations,
)
from linkcv.domain.resume.source_graph import (
    ParsedSourceBlock,
    build_source_graph,
    build_source_graph_for_import,
    build_source_graph_from_ir,
    build_source_graph_from_layout_ir,
    source_document_sha256,
    stable_source_id,
)
from linkcv.domain.resume.composer import (
    CanonicalCompositionError,
    CanonicalCompositionResult,
    compose_canonical_resume,
    compose_canonical_resume_document,
    compose_import_document,
    compose_resume_document,
)
from linkcv.domain.resume.layout import (
    LayoutCompilationError,
    build_layout_plan,
    compile_layout_plan,
    compile_resume_layout,
    compile_template_layout,
)

__all__ = [
    "CanonicalResumeDocument",
    "InlineIcon",
    "InlineIconName",
    "CanonicalCompositionError",
    "CanonicalCompositionResult",
    "LayoutPlan",
    "LayoutCompilationError",
    "RowBlock",
    "RowCell",
    "ParsedSourceBlock",
    "ResumePresentation",
    "SourceGraph",
    "SparseResumeAnnotations",
    "TemplateDefinition",
    "TemplateAvatar",
    "canonical_json_bytes",
    "canonical_sha256",
    "build_source_graph",
    "build_source_graph_for_import",
    "build_source_graph_from_ir",
    "build_source_graph_from_layout_ir",
    "source_document_sha256",
    "stable_source_id",
    "build_layout_plan",
    "compile_layout_plan",
    "compile_resume_layout",
    "compile_template_layout",
    "compose_canonical_resume",
    "compose_canonical_resume_document",
    "compose_import_document",
    "compose_resume_document",
    "validate_layout_coverage",
    "validate_source_closure",
    "validate_sparse_annotations",
]
