-- Upgrade migration for 0106: add_job_resume_matches
CREATE TABLE job_resume_matches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  user_id BIGINT UNSIGNED NOT NULL COMMENT '所有者',
  job_description_id BIGINT UNSIGNED NOT NULL COMMENT '被分析的岗位',
  resume_id BIGINT UNSIGNED NOT NULL COMMENT '被分析的简历',
  status VARCHAR(16) NOT NULL COMMENT 'pending 进行中、ready 成功、failed 失败',
  score TINYINT UNSIGNED NULL COMMENT '匹配分 0-100，仅成功时有值',
  result_json JSON NULL COMMENT '要求逐条结果与高亮词，仅成功时有值',
  jd_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '分析所用岗位内容的哈希',
  resume_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '分析所用简历内容的哈希',
  source VARCHAR(8) NOT NULL COMMENT 'auto 首页自动、manual 用户手动',
  attempts TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前内容版本下的失败与接管次数',
  lease_token CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '当前持有计算的令牌',
  lease_until DATETIME(6) NULL COMMENT '租约到期时间 UTC',
  error_code VARCHAR(64) NULL COMMENT '最近一次失败的错误码',
  analyzed_at DATETIME(6) NULL COMMENT '最近一次成功时间 UTC',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间 UTC',
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间 UTC',
  CONSTRAINT pk_job_resume_matches PRIMARY KEY (id),
  CONSTRAINT uk_job_resume_matches_job_resume UNIQUE (job_description_id, resume_id),
  CONSTRAINT fk_job_resume_matches_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_job_resume_matches_job FOREIGN KEY (job_description_id) REFERENCES job_descriptions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_job_resume_matches_resume FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE RESTRICT,
  CONSTRAINT ck_job_resume_matches_status CHECK (status IN ('pending', 'ready', 'failed')),
  CONSTRAINT ck_job_resume_matches_source CHECK (source IN ('auto', 'manual')),
  CONSTRAINT ck_job_resume_matches_score CHECK (score IS NULL OR score <= 100),
  CONSTRAINT ck_job_resume_matches_ready CHECK ((status = 'ready') = (score IS NOT NULL AND result_json IS NOT NULL)),
  INDEX idx_job_resume_matches_user_resume_score (user_id, resume_id, status, score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='岗位与简历的 AI 匹配分析结果';
