CREATE TABLE dataset_transcription_tasks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '任务自增主键',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '所属用户',
    dataset_id BIGINT UNSIGNED NOT NULL COMMENT '原音频资料',
    interview_session_id BIGINT UNSIGNED NULL COMMENT '发起时场次',
    client_request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '客户端幂等 UUID',
    status VARCHAR(16) NOT NULL DEFAULT 'queued' COMMENT '任务状态',
    route_snapshot JSON NOT NULL COMMENT '非秘密模型线路快照',
    provider_task_id VARCHAR(64) NULL COMMENT '供应商任务标识',
    result_json JSON NULL COMMENT '版本化文字与句子时间结果',
    error_code VARCHAR(64) NULL COMMENT '脱敏错误码',
    lease_token CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '后台领取令牌',
    lease_until DATETIME(6) NULL COMMENT '领取有效时间 UTC',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间 UTC',
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '最后处理时间 UTC',
    PRIMARY KEY (id),
    UNIQUE KEY uk_transcription_user_request (user_id, client_request_id),
    KEY idx_transcription_dataset (dataset_id, id),
    KEY idx_transcription_poll (status, updated_at, id),
    KEY idx_transcription_session (interview_session_id, status),
    CONSTRAINT fk_transcription_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_transcription_dataset FOREIGN KEY (dataset_id) REFERENCES user_dataset(id) ON DELETE CASCADE,
    CONSTRAINT fk_transcription_session FOREIGN KEY (interview_session_id) REFERENCES interview_sessions(id) ON DELETE SET NULL,
    CONSTRAINT ck_transcription_status CHECK (status IN ('queued','submitting','transcribing','ready','failed','cancelled')),
    CONSTRAINT ck_transcription_terminal_lease CHECK (status IN ('queued','submitting','transcribing') OR (lease_token IS NULL AND lease_until IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='面试录音异步识别任务及可校对稿件';
