using System.Text.Json.Nodes;
using DrawOffer.Core.Models;
using Xunit;
namespace DrawOffer.Core.Tests;
public class DatasetLibraryTests {
    [Fact] public void NarrowLibraryRoutesRejectArbitraryPaths(){foreach(var (path,method) in new[]{("/api/datasets","POST"),("/api/datasets/folders/1","DELETE"),("/api/datasets/1/source","GET"),("/api/datasets/1/file","PUT"),("/api/datasets/move-batch","POST"),("/api/interview-sessions/2/assets/attach","POST"),("/api/interview-sessions/2/assets/1","DELETE")})Assert.True(CareerRequest.Allowed(path,method));foreach(var path in new[]{"/api/datasets/01/source","/api/datasets/1/../source","/api/datasets/1/source?token=x","/api/datasets/1/source/","/api/datasets/1/signed-url","/api/datasets/١/source","https://evil.invalid/api/datasets"})Assert.False(DatasetRequest.Allowed(path,"GET"));Assert.False(DatasetRequest.Allowed("/api/interview-sessions/2/assets/upload","POST"));}
    [Fact] public void SnapshotIsImmutableAcrossRetryAndCleanup(){var directory=DatasetUpload.PrivateDirectory();try{var original=Path.Combine(directory,"fictional.md");File.WriteAllText(original,"# fictional original");var upload=DatasetUpload.Snapshot(original,"1",1024);try{File.WriteAllText(original,"changed externally");Assert.Equal("# fictional original",File.ReadAllText(upload.File));Assert.Equal(upload.Id,(upload with{}).Id);Assert.Equal("1",upload.Folder);Assert.NotEqual(upload.Id,(upload with{Id=Guid.NewGuid().ToString("D")}).Id);Assert.Throws<InvalidDataException>(()=>DatasetUpload.Snapshot(original,"../1",1024));Assert.Throws<InvalidDataException>(()=>DatasetUpload.Snapshot(original,"1",1));if(!OperatingSystem.IsWindows()){Assert.Equal(UnixFileMode.UserRead|UnixFileMode.UserWrite|UnixFileMode.UserExecute,File.GetUnixFileMode(upload.Directory));Assert.Equal(UnixFileMode.UserRead|UnixFileMode.UserWrite,File.GetUnixFileMode(upload.File));}}finally{upload.Discard();}Assert.False(Directory.Exists(upload.Directory));}finally{Directory.Delete(directory,true);}}
    [Fact] public void MediaReadyWithoutParsing(){var media=new DatasetRecord(JsonNode.Parse("""{"asset_kind":"audio","upload_status":"succeeded","parse_status":null}""")!);Assert.True(media.Ready);Assert.False(media.Retryable);var doc=new DatasetRecord(JsonNode.Parse("""{"asset_kind":"document","upload_status":"succeeded","parse_status":"failed"}""")!);Assert.True(doc.Retryable);Assert.False(doc.Ready);}

    [Fact] public async Task RealTransferUsesStableKeyPrivateCookieAndRejectsRedirectsAndOversize(){
        using var listener=new System.Net.Sockets.TcpListener(System.Net.IPAddress.Loopback,0);listener.Start();
        var origin=new Uri($"http://127.0.0.1:{((System.Net.IPEndPoint)listener.LocalEndpoint).Port}/");using var timeout=new CancellationTokenSource(TimeSpan.FromSeconds(15));var requests=new List<string>();
        var server=Task.Run(async()=>{for(var index=0;index<4;index++){using var socket=await listener.AcceptTcpClientAsync(timeout.Token);await using var stream=socket.GetStream();var bytes=new byte[8192];var text="";while(!text.Contains("\r\n\r\n")){var read=await stream.ReadAsync(bytes,timeout.Token);if(read==0)break;text+=System.Text.Encoding.UTF8.GetString(bytes,0,read);}var split=text.IndexOf("\r\n\r\n",StringComparison.Ordinal);var header=text[..split];var lengthLine=header.Split("\r\n").FirstOrDefault(x=>x.StartsWith("Content-Length:",StringComparison.OrdinalIgnoreCase));var length=lengthLine is null?0:int.Parse(lengthLine.Split(':')[1].Trim());while(System.Text.Encoding.UTF8.GetByteCount(text[(split+4)..])<length){var read=await stream.ReadAsync(bytes,timeout.Token);if(read==0)break;text+=System.Text.Encoding.UTF8.GetString(bytes,0,read);}if(lengthLine is null&&index<2)while(!text.EndsWith("\r\n0\r\n\r\n",StringComparison.Ordinal)){var read=await stream.ReadAsync(bytes,timeout.Token);if(read==0)break;text+=System.Text.Encoding.UTF8.GetString(bytes,0,read);}requests.Add(text);var body=index<2?"{\"id\":\"1\"}":"fictional-source";var status=index==1?$"302 Found\r\nLocation: {origin}redirect-target":"200 OK";var response=System.Text.Encoding.UTF8.GetBytes($"HTTP/1.1 {status}\r\nSet-Cookie: library=private; Path=/\r\nContent-Type: {(index<2?"application/json":"text/plain")}\r\nContent-Length: {body.Length}\r\nConnection: close\r\n\r\n{body}");await stream.WriteAsync(response,timeout.Token);}},timeout.Token);
        var directory=DatasetUpload.PrivateDirectory();try{var source=Path.Combine(directory,"fictional.md");File.WriteAllText(source,"# fictional bytes");var upload=DatasetUpload.Snapshot(source,"7",1024);try{using var transport=new DrawOffer.Core.Api.DesktopTransport(origin,allowLocalHttp:true);Assert.Equal("1",(await transport.UploadDatasetAsync(upload,"fixture-access",timeout.Token))["id"]!.GetValue<string>());var rejected=await Assert.ThrowsAsync<DrawOffer.Core.Api.ApiException>(()=>transport.UploadDatasetAsync(upload,"fixture-access",timeout.Token));Assert.Equal(System.Net.HttpStatusCode.Found,rejected.Status);var target=Path.Combine(directory,"download");await transport.DownloadDatasetAsync("1",target,100,"fixture-access",timeout.Token);Assert.Equal("fictional-source",File.ReadAllText(target));await Assert.ThrowsAsync<InvalidDataException>(()=>transport.DownloadDatasetAsync("1",target,2,"fixture-access",timeout.Token));await server;Assert.Equal(4,requests.Count);Assert.All(requests,r=>{Assert.DoesNotContain("\r\nCookie:",r,StringComparison.OrdinalIgnoreCase);Assert.Contains("Bearer fixture-access",r);});Assert.All(requests.Take(2),r=>{Assert.Contains(upload.Id,r);Assert.Contains("# fictional bytes",r);Assert.Contains("folder_id",r);});}finally{upload.Discard();}}finally{Directory.Delete(directory,true);}
    }
}
