import { getLocale } from "@/i18n";

// Landing-only copy. Keys are the Chinese source text, matching the app-wide `t()` convention.
const en: Record<string, string> = {
  // Navigation
  "产品": "Product", "使用场景": "Use cases", "了解更多": "Learn more", "更多细节": "Details", "功能演示": "Features",
  "工作区": "Workspace", "一体化工作台": "All-in-one workspace", "AI 助手": "AI assistant", "岗位看板": "Job board", "模拟面试": "Mock interviews",
  "多模型选择": "Model choice", "导入已有简历": "Import a resume", "模板与中文排版": "Templates & typography",
  "求职准备": "Job prep", "按 JD 改简历": "Tailor to the JD", "面试评估报告": "Interview reports",
  "写好经历": "Tell your story", "整理项目资料": "Organize project notes", "让 AI 完成修改": "Let AI make the edits", "针对岗位准备简历": "Prepare for each role",
  "准备机会": "Chase the offer", "管理求职进程": "Track applications", "练习项目追问": "Practice follow-ups",
  "顺手准备": "Small helpers", "资料随手引用": "Quick references", "岗位快速收集": "Quick job capture", "求职偏好": "Job preferences",
  "探索": "Explore", "产品能力": "Capabilities", "常见问题": "FAQ", "产品理念": "Our approach", "从哪里开始": "Where to start",
  "免费开始": "Start free", "跳到主要内容": "Skip to main content", "主导航": "Main navigation", "LinkResume 首页": "LinkResume home",
  "打开导航菜单": "Open navigation menu", "关闭导航菜单": "Close navigation menu", "切换语言": "Switch language",
  // Hero
  "懂你经历的求职搭档。": "The job-search partner that knows your story.",
  "它读过你的简历、项目和面试记录，帮你改简历、对岗位、练面试。": "It has read your resume, projects and interview notes, and helps you edit, match roles and practice.",
  "每一步怎么走，还是你说了算。": "You still decide every step.",
  "看 2 分钟演示": "Watch the 2-min demo", "看演示": "Watch demo",
  "免费使用 · 支持导入 PDF / Word / Markdown 简历": "Free to use · Import PDF / Word / Markdown resumes",
  "LinkResume 产品首页演示": "LinkResume product demo", "互动演示 · 示例数据": "Interactive demo · Sample data",
  "LinkResume 产品互动演示 · 示例数据": "LinkResume interactive demo · Sample data",
  // Stats
  "求职者": "Job seekers", "份简历": "Resumes", "次岗位匹配": "Job matches", "场模拟面试": "Mock interviews run",
  "30,000+ 求职者正在用 LinkResume 准备求职（示例数据）": "30,000+ job seekers prepare with LinkResume (sample data)",
  // CTAs
  "现在开始": "Get started", "每场面试，都有备而来。": "Walk into every interview prepared.", "准备求职的新方式。": "A new way to prepare for your job search.",
  // FAQ
  "还有疑问？": "Still have questions?", "没有找到答案？写信给我们：": "Didn't find an answer? Write to us:",
  "LinkResume 免费吗？": "Is LinkResume free?",
  "简历编辑、导出和岗位看板都可以免费使用；AI 相关能力按用量提供免费额度，后续会推出更多方案。": "Resume editing, export and the job board are free. AI features include a free usage allowance, and more plans are on the way.",
  "我的简历数据安全吗？": "Is my resume data safe?",
  "简历、岗位和资料保存在你自己的账号里，只在你发起编辑、分析或模拟面试时使用；不需要的内容可以随时删除。": "Resumes, jobs and notes stay in your own account and are used only when you start an edit, analysis or mock interview. Delete anything at any time.",
  "支持导入哪些格式的简历？": "Which resume formats can I import?",
  "支持 PDF、Word（DOCX）和 Markdown，导入后会整理成可以直接编辑的简历。": "PDF, Word (DOCX) and Markdown. Imports become a resume you can edit right away.",
  "AI 使用的是哪些模型？": "Which AI models are used?",
  "对话中可以切换 DeepSeek 等模型，实际可用的模型以工作区里的列表为准。": "You can switch between models such as DeepSeek in a conversation. The workspace list shows what is available.",
  "可以导出成什么格式？": "What can I export to?",
  "简历导出为 PDF，可以按标准 A4 分页，也可以用智能一页把内容收进一张连续页面。": "Resumes export to PDF, either paginated as standard A4 or fitted onto one continuous page with Smart One Page.",
  // Footer
  "产品功能": "Product", "了解 LinkResume": "About LinkResume", "返回顶部": "Back to top", "页脚导航": "Footer navigation",
  "岗位与简历联动": "Jobs linked to resumes", "求职进程管理": "Application tracking", "面试准备": "Interview prep",
  // Feature showcase
  "它能帮你做什么": "What it does for you", "求职要用的，都连在一起。": "Everything your job search needs, connected.",
  "一个岗位的所有东西，都在一处。": "Everything for one role, in one place.",
  "简历、JD、面试录音和复盘都挂在岗位下。二面之前，它已经帮你把准备清单列好。": "Resume, JD, interview recordings and reviews all live under the role. Before round two, your prep checklist is ready.",
  "它来动笔，你来拍板。": "It writes. You decide.",
  "它读完你的项目复盘，找出简历里漏掉的成果，写好修改等你确认。": "It reads your project review, finds results your resume missed, and drafts edits for you to approve.",
  "投之前，先对一遍 JD。": "Check the JD before you apply.",
  "它逐条对照岗位要求，告诉你哪些已经命中、还差什么，再帮你按 JD 改简历。": "It checks each requirement, shows what you already cover and what's missing, then tailors your resume.",
  "每个岗位走到哪，一眼看清。": "See where every application stands.",
  "拖一下卡片就能推进阶段，面试时间和记录跟着岗位走。": "Drag a card to move it forward. Interview times and notes stay with the role.",
  "面试官会追问的，先练一遍。": "Rehearse the follow-up questions first.",
  "它按你的简历出题、追问、打分，再告诉你下次可以怎么答。": "It asks questions from your resume, follows up, scores you and suggests better answers.",
  "岗位详情：求职进度、关联资料与二面准备清单（示例数据）": "Job detail: progress, linked materials and round-two checklist (sample data)",
  "AI 助手读取简历、项目复盘和 JD 后给出修改建议（示例数据）": "The AI assistant reads the resume, project review and JD, then suggests edits (sample data)",
  "岗位要求逐条对照与 82 分匹配分析（示例数据）": "Requirement-by-requirement check with an 82-point match (sample data)",
  "岗位看板：拖动卡片推进求职阶段（示例数据）": "Job board: drag a card to the next stage (sample data)",
  "模拟面试：主问题、追问与评估报告（示例数据）": "Mock interview: question, follow-up and report (sample data)",
  // Scene 1
  "高级产品经理": "Senior PM", "正式": "Full-time", "星河科技": "Galaxy Tech", "上海": "Shanghai", "20–30K × 14 薪": "¥20–30K × 14",
  "二面": "Round 2", "今天 14:00": "Today 14:00", "求职进度": "Progress", "5 条记录": "5 entries",
  "投递": "Applied", "产品经理简历\u2003\u20039月12日": "PM resume\u2003\u2003Sep 12", "已投递": "Sent", "简历筛选": "Screening", "9月15日": "Sep 15", "已通过": "Passed",
  "一面\u2002视频面试": "Round 1 video", "9月24日 10:00": "Sep 24 10:00", "复盘 8.2": "Review 8.2",
  "10月4日 14:00–15:00": "Oct 4 14:00–15:00", "还有 16 天回复": "Reply due in 16 days", "等待中": "Waiting",
  "关联资料": "Linked materials", "4 个": "4 items", "产品经理简历": "PM resume", "投递简历": "Submitted resume", "星河科技 JD": "Galaxy Tech JD", "岗位 JD": "Job JD",
  "项目复盘.md": "project-review.md", "岗位资料": "Job notes", "一面录音与记录": "Round 1 recording", "录音与记录\u2003\u200332 分钟": "Recording & notes\u2003\u200332 min",
  "二面准备清单": "Round 2 checklist", "今天 14:00 现场面试": "Today 14:00 onsite",
  "复习一面复盘里的 2 个追问": "Review 2 follow-ups from round 1", "整理审批配置项目的灰度数据": "Gather rollout data for the approvals project",
  "模拟一轮业务面，练习回应追问": "Run a mock interview with follow-ups", "开始模拟面试": "Start mock interview",
  // Scene 2
  "复盘里有 4 条可量化结果，简历目前一条都没用上。对照 JD 的「数据驱动」要求，我准备了 2 处修改。": "Your review has 4 measurable results, and the resume uses none of them. For the JD's \"data-driven\" requirement, I drafted 2 edits.",
  "按这个 JD，把复盘里的结果整理进简历。": "Use this JD to bring the review's results into my resume.",
  "已分析 3 份资料，提取 4 条可量化结果": "Read 3 files, found 4 measurable results",
  "张三": "Alex Zhang", "求职意向：高级产品经理（B 端 SaaS）": "Objective: Senior PM (B2B SaaS)", "工作经历": "Experience",
  "2021.07 – 至今": "2021.07 – Present",
  "负责企业审批与权限模块，服务 3,000+ 家企业客户，月活管理员 4.2 万。": "Owned approvals and permissions for 3,000+ business customers and 42K monthly admins.",
  "项目经历": "Projects", "审批配置体验优化": "Approval setup redesign",
  "主导审批配置改版：基于 1,200+ 条工单归因出 3 类高频问题，两轮原型测试后重构配置路径；灰度期任务完成率 71% → 86%，平均配置时长缩短 42%。": "Led the approval setup redesign: traced 1,200+ tickets to 3 core issues and rebuilt the flow after two prototype rounds; completion rose 71% → 86% and setup time fell 42%.",
  "联合研发、运营梳理 23 个配置项，沉淀 6 套行业模板，新客户上线周期从 14 天缩短至 5 天。": "Mapped 23 settings with engineering and ops into 6 industry templates, cutting onboarding from 14 days to 5.",
  "教育经历": "Education", "建议修改": "Suggested edits", "2 项待确认": "2 to review", "量化项目结果": "Quantify results", "补充协作范围": "Add team scope",
  "原文": "Original", "负责审批配置功能优化，通过原型测试改进配置流程，提升了用户体验。": "Improved approval setup through prototype testing, enhancing the user experience.",
  "建议": "Suggested", "主导审批配置改版：基于 ": "Led the approval setup redesign: traced ", " 条工单归因出 3 类高频问题，两轮原型测试后重构配置路径；灰度期任务完成率 ": " tickets to 3 core issues and rebuilt the flow; completion rose ",
  "，平均配置时长缩短 ": " and setup time fell ", "。": ".",
  "忽略": "Skip", "采用此项": "Apply", "全部采用": "Apply all",
  // Scene 3
  "岗位描述": "Job description", "9月12日导入": "Imported Sep 12", "岗位职责": "Responsibilities",
  "负责企业审批与流程引擎的产品规划，提升配置效率与易用性。": "Plan the enterprise approvals and workflow engine, making setup faster and easier.",
  "通过数据分析与用户研究定位问题，推动方案落地并验证效果。": "Find problems through data and research, ship solutions and measure the impact.",
  "任职要求": "Requirements", "5 年以上 B 端产品经验": "5+ years in B2B product", "熟悉审批、权限或工作流类产品": "Approvals, permissions or workflow products",
  "能用 SQL 独立完成数据分析": "Independent data analysis with SQL", "具备用户研究与原型设计能力": "User research and prototyping",
  "有 SaaS 商业化或定价经验": "SaaS monetization or pricing", "能推动研发、设计与运营跨团队协作": "Lead work across eng, design and ops",
  "已命中": "Matched", "待补充": "Missing", "匹配度": "Match", "基于「产品经理简历」": "Based on \"PM resume\"",
  "还缺：SQL 数据分析、SaaS 商业化经验": "Missing: SQL analysis, SaaS monetization", "已命中\u20026": "Matched 6", "待补充\u20022": "Missing 2",
  "B 端产品": "B2B product", "审批流程": "Approvals", "权限设计": "Permissions", "用户研究": "User research", "原型设计": "Prototyping",
  "跨团队协作": "Cross-team", "SaaS 商业化": "SaaS monetization", "重新分析": "Re-analyze", "按 JD 优化简历": "Tailor to JD",
  // Scene 4
  "筛选中": "Screening", "笔试": "Test", "一面": "Round 1",
  "北辰数据": "Polaris Data", "数据产品经理": "Data PM", "投递于 9月30日": "Applied Sep 30", "澄海科技": "Clearsea Tech", "产品运营": "Product Ops",
  "校招": "Graduate", "投递于 10月1日": "Applied Oct 1", "星图云": "Startu Cloud", "B 端产品经理": "B2B PM", "投递于 9月28日": "Applied Sep 28",
  "拾光互娱": "Glimmer Games", "游戏策划": "Game Designer", "截止 10月8日 18:00": "Due Oct 8 18:00", "云杉医疗": "Spruce Health", "产品经理": "PM",
  "10月9日 10:00": "Oct 9 10:00", "远航物流": "Voyage Logistics", "9月26日 获得 Offer": "Offer on Sep 26", "蓝鲸支付": "Bluewhale Pay", "10月10日 15:00": "Oct 10 15:00",
  "9 个求职进程": "9 applications", "看板": "Board", "列表": "List", "+ 新建求职": "+ New application", "推进到二面": "Moved to round 2", "10月12日 14:00": "Oct 12 14:00",
  // Scene 5
  "先从 1,200 多条工单里做归因，发现 3 类高频问题都出在配置路径上。两轮原型测试后重构了流程，灰度期任务完成率从 71% 提升到 86%……": "I traced 1,200+ tickets and found 3 frequent issues in the setup flow. After two prototype rounds we rebuilt it, and completion rose from 71% to 86%…",
  "结构清晰": "Structure", "数据支撑": "Evidence", "回应追问": "Follow-ups",
  "星河科技\u2002高级产品经理": "Galaxy Tech  Senior PM", "已用时": "Elapsed", "放弃": "Quit", "结束并评估": "Finish & score", "作答进度": "Progress", "第 3 / 6 题": "Question 3 / 6",
  "主问题": "Question", "你是如何发现审批配置的问题，并验证优化效果的？": "How did you find the approval setup problem and verify the fix?",
  "追问 L1": "Follow-up L1",
  "完成率的提升，你怎么确认是配置路径改动带来的，而不是其他因素？": "How do you know the higher completion came from the new flow and not something else?",
  "输入你的回答…": "Type your answer…", "评估报告": "Report", "亮点": "Strength", "用工单归因和灰度数据讲清了因果。": "Ticket analysis and rollout data made the cause clear.",
  "待改进": "To improve", "被追问对照组时有些犹豫，可以补充 A/B 实验设计。": "Hesitated on the control group. Add the A/B test design.", "查看完整报告 →": "View full report →",
  // Detail cards
  "细节": "Details", "省时间的小细节。": "Small details that save time.", "换模型、导入简历、存岗位，这些顺手的事它都想到了。": "Switch models, import resumes, save jobs. The small things are handled.",
  "换个模型，对话不断。": "Switch models mid-chat.", "DeepSeek、Claude、GPT 随时切换，不用离开当前对话。": "Move between DeepSeek, Claude and GPT without leaving the conversation.",
  "在对话输入框中选择 DeepSeek、Claude、GPT、Gemini 或 Kimi": "Choose DeepSeek, Claude, GPT, Gemini or Kimi in the chat composer",
  "模型品牌示例，实际可用模型以工作区列表为准。": "Model brands are examples; the workspace list shows what is available.",
  "已有简历导入": "Resume import", "旧简历拖进来就能改。": "Drop in an old resume and edit.", "导入 PDF、Word 或 Markdown，它会整理成可以直接编辑的简历。": "Import PDF, Word or Markdown and get a resume you can edit right away.",
  "导入 PDF 简历后识别出教育、工作、项目和技能四个模块": "A PDF resume imported into education, experience, projects and skills",
  "排版细到行距。": "Typography down to line height.", "选好模板，再细调字体、字号和行距。": "Pick a template, then fine-tune font, size and spacing.",
  "简历排版面板：思源宋体、11 号字、1.5 倍行距": "Typography panel: Source Han Serif, 11 pt, 1.5 line height",
  "@ 一下，资料就在对话里。": "@ mention, and it's in the chat.", "项目复盘、面试笔记、岗位 JD，聊的时候直接 @ 进来，原文随时能看。": "Project reviews, interview notes and JDs come in with an @, and the original is always one click away.",
  "在对话中用 @ 引用项目复盘、面试笔记、岗位和简历": "Use @ to reference reviews, notes, jobs and resumes in a chat",
  "粘贴招聘文字，岗位就存好了。": "Paste a job post, and it's saved.", "粘贴招聘文字或截图，它识别关键信息，你核对一下就能保存。": "Paste text or a screenshot. It pulls out the key details for you to check and save.",
  "从粘贴的招聘文字中识别公司、岗位、城市、薪资、经验和类型": "Company, title, city, salary, experience and type extracted from a pasted post",
  "个性化求职偏好": "Personal preferences", "说一次偏好，之后都记得。": "Say it once, and it remembers.", "设好城市、薪资和工作类型，建议会跟着调整。": "Set city, salary and job type, and suggestions adapt.",
  "求职偏好：期望城市、期望薪资和工作类型": "Preferences: cities, salary and job type",
  "选择模型": "Choose model", "默认": "Default", "问点什么，或输入 @ 引用资料": "Ask anything, or type @ to reference",
  "导入简历": "Import resume", "张三_产品经理_2026.pdf": "alex_zhang_pm_2026.pdf", "识别到 4 个模块": "4 sections found",
  "1 段": "1", "3 段": "3", "2 个": "2", "专业技能": "Skills", "8 项": "8",
  "星图软件": "Startu Software", "2023.07 – 至今": "2023.07 – Present",
  "负责 B 端协同产品的增长，搭建新用户引导流程，次月留存提升 12%。": "Drove growth for a B2B collaboration product; new onboarding lifted month-2 retention 12%.",
  "主导 3 次定价实验，付费转化率从 4.1% 提升到 5.6%。": "Led 3 pricing experiments, raising paid conversion from 4.1% to 5.6%.",
  "排版": "Typography", "字体": "Font", "思源宋体": "Source Han Serif", "字号": "Size", "行距": "Spacing",
  "增长实验复盘.md": "growth-review.md", "资料": "Note", "二面准备笔记": "Round 2 notes", "岗位": "Job", "简历": "Resume", "张三\u2002产品经理简历": "Alex Zhang · PM resume",
  "可引用的资料和简历": "Notes and resumes", "结合": "Use", "准备二面回答": "to prep round 2", "@ 引用": "@ mention",
  "公司": "Company", "云帆科技": "Cloudsail Tech", "增长产品经理": "Growth PM", "城市": "City", "杭州": "Hangzhou", "薪资": "Salary",
  "25–35K × 15 薪": "¥25–35K × 15", "经验": "Experience", "3–5 年": "3–5 yrs", "类型": "Type",
  "粘贴岗位文字": "Pasted job post", "已识别 6 项": "6 fields found", "核对后保存": "Check, then save", "保存岗位": "Save job",
  "【云帆科技】增长产品经理\n杭州 余杭区  25-35K·15薪\n经验 3-5 年  本科\n\n岗位职责：\n1. 负责新用户增长策略，设计并推动拉新、激活实验；\n2. 搭建增长数据看板，定位转化漏斗中的关键问题；": "[Cloudsail Tech] Growth PM\nHangzhou, Yuhang  ¥25-35K × 15\n3-5 yrs  Bachelor's\n\nResponsibilities:\n1. Own new-user growth; design and run acquisition and activation experiments;\n2. Build growth dashboards and find key drop-offs in the funnel;",
  "AI 讨论时会参考这些信息": "AI uses these in conversations", "期望城市": "Cities", "+ 添加": "+ Add", "期望薪资": "Salary", "/ 月": "/ mo",
  "工作类型": "Job type", "实习": "Internship",
  // Split labels and initials
  "现场面试": "onsite", "业务面": "Business round", "6 个考察点": "6 topics", "中级难度": "Medium", "你的回答": "Your answer", "186 字": "186 words", "语音输入": "Voice",
  "Enter 发送": "Enter to send", "Shift + Enter 换行": "Shift + Enter for new line", "上一场": "Last", "一面模拟": "Round 1 mock", "已解析": "Parsed",
  "华东理工大学": "ECUST", "工商管理": "Business Admin.",
  "星": "G", "北": "P", "澄": "C", "图": "S", "拾": "G", "云": "S", "远": "V", "鲸": "B",
};

/** Only call with landing-owned copy; render from a component that subscribes via `useLocale()`. */
export function lt(text: string): string {
  return getLocale() === "en-US" ? en[text] ?? text : text;
}
