import { getInputProps } from "remotion";

/** 短片语言：渲染时用 `--props='{"locale":"en"}'` 输出英文版，默认中文。 */
export const LOCALE: "zh" | "en" = (getInputProps() as { locale?: string }).locale === "en" ? "en" : "zh";

/** 以中文原文为键的英文文案；英文版缺译时直接报错，避免漏翻的中文出现在画面里。 */
const EN: Record<string, string> = {
  // 开场
  "简历": "Resumes",
  "岗位": "Jobs",
  "面试": "Interviews",
  "复盘": "Reviews",
  "简历_v3_最终版.pdf": "resume_v3_final.pdf",
  "简历_v5_真的最终.docx": "resume_v5_FINAL_final.docx",
  "项目经历草稿": "Project notes (draft)",
  "两分钟自我介绍": "2-min self-intro",
  "星河科技 · Java 后端": "Xinghe Tech · Java Backend",
  "北辰互娱 · 服务端开发": "Beichen Games · Server Dev",
  "云栈科技 · 后端开发": "Yunzhan Tech · Backend",
  "数澜网络 · Java 开发": "Shulan Network · Java Dev",
  "一面录音 · 42:18": "Round 1 recording · 42:18",
  "二面 · 周四 14:00": "Round 2 · Thu 14:00",
  "笔试 · 周三 19:30": "Online test · Wed 19:30",
  "HR：方便发下最新简历吗？": "HR: Could you send your latest resume?",
  "线上 Full GC 怎么排查？": "How to debug frequent Full GC?",
  "被问到 G1 和 ZGC": "Got asked G1 vs. ZGC",
  "Redis 一致性答得一般": "Shaky on Redis consistency",
  "下次补上调优数据": "Add tuning numbers next time",
  "简历、岗位、面试，散落在各处": "Resumes, jobs, interviews, scattered everywhere",
  "模拟面试": "Mock interview",
  "星河科技": "Xinghe Tech",
  "每一次投递和面试，都不该白费": "Every application and interview should count",
  "懂你经历的求职搭档": "The job-search partner that knows your story",

  // 简历
  "周屿": "Yu Zhou",
  "｜": "|",
  "江城大学 · 计算机科学与技术 · 本科 · 2022.09 – 2026.06": "Jiangcheng University · B.S. Computer Science · 2022.09 – 2026.06",
  "联系方式": "Contact",
  "教育背景": "Education",
  "联系方式教育背景｜": "Contact Education |",
  "实习经历": "Internships",
  "项目经历": "Projects",
  "专业技能": "Skills",
  "荣誉奖项": "Awards",
  "云栈科技": "Yunzhan Tech",
  "Java 后端开发实习": "Java Backend Intern",
  "技术栈：Java、Spring Boot、MySQL、Redis、Kafka": "Stack: Java, Spring Boot, MySQL, Redis, Kafka",
  "1. 负责订单服务拆分重构，将单体下单链路拆为订单、库存、支付三个服务，核心接口 P99 延迟从 420ms 降至 160ms；": "1. Split the monolithic order flow into order, inventory and payment services; core API P99 down from 420ms to 160ms;",
  "2. 设计 Redis + Lua 库存预扣方案，解决大促超卖问题，峰值 QPS 8000；": "2. Designed Redis + Lua stock pre-deduction to stop overselling at 8,000 peak QPS;",
  "3. 参与 JVM 调优，排查线上 Full GC 频繁问题。": "3. Took part in JVM tuning and frequent Full GC troubleshooting.",
  "3. 定位大对象缓存导致的 Full GC 频繁，调整 G1 参数与缓存淘汰策略，Full GC 由每小时 6 次降至 0，Young GC 停顿降低 35%；": "3. Traced frequent Full GC to oversized cached objects; tuned G1 and cache eviction, cutting Full GC from 6/hour to 0 and Young GC pauses by 35%;",
  "数澜网络": "Shulan Network",
  "后端开发实习": "Backend Intern",
  "1. 基于 Kafka 实现用户行为日志异步落库，削峰后数据库写入压力降低 60%；": "1. Async behavior-log ingestion via Kafka, cutting database write pressure by 60%;",
  "2. 编写 MyBatis 批量写入组件，10 万条数据导入耗时由 95s 降至 12s。": "2. Built a MyBatis batch writer: 100k-row imports down from 95s to 12s.",
  "分布式秒杀系统": "Distributed Flash-Sale System",
  "个人项目": "Personal project",
  "1. 使用 Redis 预减库存 + MQ 异步下单，支撑 1 万并发压测无超卖；": "1. Redis pre-deduction + MQ async orders; no overselling at 10k concurrency;",
  "2. 通过本地缓存和布隆过滤器解决了缓存穿透问题并且把接口命中率提升到了 98%。": "2. Used a local cache and a Bloom filter to solve cache penetration and raised the API hit rate to 98% in the end.",
  "• 熟悉 Java 集合与并发编程，了解 JVM 内存模型与垃圾回收机制；": "• Java collections and concurrency; JVM memory model and GC;",
  "• 熟悉 MySQL 索引与事务隔离级别，掌握 Redis 常用数据结构与持久化；": "• MySQL indexing and isolation levels; Redis data structures and persistence;",
  "• 熟悉 Spring Boot、MyBatis，了解 Kafka、Docker 与 Linux 常用命令。": "• Spring Boot, MyBatis, Kafka, Docker and everyday Linux.",
  "• 校级程序设计竞赛一等奖（2024）": "• 1st Prize, University Programming Contest (2024)",
  "• 校级一等奖学金（2 次）": "• First-class Scholarship (twice)",
  "AI 检查": "AI check",
  "调优缺少前后数据": "Tuning lacks before/after data",
  "缺信息": "Missing info",
  "补充 Full GC 频率、停顿时间的变化，结果更可信": "Add Full GC frequency and pause changes to make it credible",
  "建议改写": "Suggested rewrite",
  "已采用": "Applied",
  "长句层次可更清晰": "Long sentence could be clearer",
  "表达": "Clarity",
  "拆开方案与结果，先写做法，再写收益": "Split approach and result: action first, impact second",
  "导入旧简历，秒变可编辑": "Import an old resume, edit it instantly",
  "换个模板，排版自动重排": "Switch templates, the layout reflows itself",
  "逐句检查，对着岗位改到位": "Line-by-line checks, tailored to the job",

  // 投递
  "职位详情": "Job details",
  "Java 后端开发工程师": "Java Backend Engineer",
  "星河科技 · 杭州 · 25–40K · 本科": "Xinghe Tech · Hangzhou · 25–40K · Bachelor's",
  "岗位要求": "Requirements",
  "熟悉 Java、Spring Boot，具备良好的编码习惯": "Solid Java and Spring Boot, clean coding habits",
  "熟悉 MySQL、Redis，有高并发场景经验": "MySQL and Redis in high-concurrency systems",
  "有 JVM 调优和线上问题排查经验": "JVM tuning and production troubleshooting",
  "了解 Kafka 等消息中间件": "Familiar with Kafka or similar message queues",
  "有分布式系统设计经验者优先": "Distributed system design is a plus",
  "待投递": "To apply",
  "一面": "Round 1",
  "二面": "Round 2",
  "Java 开发": "Java Developer",
  "后端开发": "Backend Developer",
  "北辰互娱": "Beichen Games",
  "服务端开发": "Server Developer",
  "Java 后端开发": "Java Backend",
  "我的简历": "My resume",
  "岗位匹配度 · 星河科技": "Job match · Xinghe Tech",
  "高并发场景经验": "High-concurrency experience",
  "JVM 调优经验 · 简历未体现": "JVM tuning · missing from resume",
  "面试日程 · 本周": "Interviews · This week",
  "周一 13": "Mon 13",
  "周二 14": "Tue 14",
  "周三 15": "Wed 15",
  "周四 16": "Thu 16",
  "周五 17": "Fri 17",
  "二面 · 北辰互娱": "Beichen · R2",
  "一面 · 星河科技": "Xinghe · R1",
  "从收藏到面试，一路跟进": "From saved job to interview, all in one place",

  // 面试
  "面试官": "Interviewer",
  "我": "Me",
  "线上 Full GC 频繁，你会怎么排查？": "Full GC keeps firing in production. How do you debug it?",
  "先看 GC 日志确认频率，再用 jmap 导出堆，分析大对象……": "Check the GC logs first, then dump the heap with jmap and look for big objects…",
  "调优前后的数据有对比吗？": "Did you compare before and after tuning?",
  "嗯……当时没有特别记录。": "Um… I didn't really record that.",
  "一面录音 · 星河科技": "Round 1 recording · Xinghe Tech",
  "AI 复盘": "AI review",
  "结果判断": "Outcome",
  "倾向通过": "Likely pass",
  "Q1 订单服务拆分": "Q1 Order service split",
  "回答扎实": "Solid",
  "拆分边界与数据一致性讲得清楚": "Clear service boundaries and data consistency",
  "Q2 Full GC 排查": "Q2 Full GC debugging",
  "缺少数据支撑": "Lacks data",
  "步骤完整，但没有调优前后的对比": "Steps complete, but no before/after comparison",
  "Q3 Redis 与 MySQL 一致性": "Q3 Redis–MySQL consistency",
  "思路清晰": "Clear reasoning",
  "能说明延迟双删的取舍": "Explains delayed double-delete trade-offs",
  "来自一面复盘 · Full GC 排查": "From Round 1 review · Full GC debugging",
  "模拟面试 · 技术面 · 针对性追问": "Mock interview · Technical · Targeted follow-up",
  "为什么选 G1，而不是 ZGC？": "Why G1 instead of ZGC?",
  "我们的堆在 8G 左右，G1 的停顿已经可控；当时的 JDK 版本也还不支持生产可用的 ZGC……": "Our heap was about 8 GB and G1 pauses were under control; our JDK had no production-ready ZGC yet…",
  "语速 · 字/分": "Pace · wpm",
  "长停顿 · 次": "Long pauses",
  "口头禅占比": "Filler words",
  "真实面试，AI 逐题复盘": "Real interviews, reviewed question by question",
  "模拟面试，追问到底": "Mock interviews that keep digging",

  // 能力图谱
  "内存模型": "Memory model",
  "类加载": "Class loading",
  "并发编程": "Concurrency",
  "线程池": "Thread pools",
  "锁与 AQS": "Locks & AQS",
  "索引": "Indexes",
  "事务": "Transactions",
  "缓存一致性": "Cache consistency",
  "分布式锁": "Distributed locks",
  "消息可靠性": "Message reliability",
  "微服务": "Microservices",
  "服务拆分": "Service split",
  "限流熔断": "Rate limiting",
  "系统设计": "System design",
  "秒杀架构": "Flash-sale design",
  "算法": "Algorithms",
  "Full GC 排查 · 缺少数据": "Full GC debugging · no data",
  "G1 与 ZGC 的取舍": "G1 vs. ZGC trade-offs",
  "Redis + Lua 库存预扣": "Redis + Lua stock pre-deduction",
  "Kafka 日志异步落库": "Kafka async log ingestion",
  "MySQL 一致性 · 思路清晰": "MySQL consistency · clear",
  "订单服务拆分 · 回答扎实": "Order service split · solid",
  "秒杀系统 · 1 万并发": "Flash sale · 10k concurrency",
  "掌握扎实": "Strong",
  "一般": "Fair",
  "有待加强": "Needs work",
  "26 个技能节点 · 来自 3 份简历、5 场面试与 7 次模拟": "26 skill nodes · from 3 resumes, 5 interviews and 7 mock sessions",
  "掌握度": "Mastery",
  "来自 3 条记录": "From 3 records",
  "一面复盘 · 星河科技": "Round 1 review · Xinghe Tech",
  "Full GC 排查缺少调优前后数据": "Full GC answer lacked before/after data",
  "模拟面试 · 第 3 题": "Mock interview · Q3",
  "G1 与 ZGC 的取舍说得不够清楚": "G1 vs. ZGC trade-offs were unclear",
  "岗位要求 · 星河科技": "Job requirements · Xinghe Tech",
  "JVM 调优经验在简历中未体现": "JVM tuning isn't shown on the resume",
  "专项练习 · JVM": "Targeted practice · JVM",
  "描述一次 Full GC 排查的完整步骤": "Walk through a Full GC investigation",
  "G1 的 Region 设计解决了什么问题": "What problem do G1 regions solve?",
  "如何按业务特点选择垃圾回收器": "Choosing a collector for your workload",
  "每一场面试，都沉淀成你的能力图谱": "Every interview builds your skill map",
  "哪里薄弱，一眼看清": "See your weak spots at a glance",
  "针对短板，专项补强": "Targeted practice for weak spots",
};

export function tr(zh: string) {
  if (LOCALE === "zh") return zh;
  const en = EN[zh];
  if (en === undefined) throw new Error(`短片缺少英文文案：${zh}`);
  return en;
}
