/** Independent visual catalog; identifiers also select the shared editor/print CSS. */
export const atlasThemes = [
  "atlas-folio-serif",
  "atlas-mono-ledger",
  "atlas-centered-rule",
  "atlas-framed-letter",
  "atlas-corner-bracket",
  "atlas-editorial-banner",
  "atlas-split-nameplate",
  "atlas-underline-tabs",
  "atlas-numbered-sections",
  "atlas-dotted-journal",
  "atlas-ruled-notebook",
  "atlas-minimal-axis",
  "atlas-slate-sidebar",
  "atlas-ivory-sidebar",
  "atlas-forest-sidebar",
  "atlas-portrait-rail",
  "atlas-boxed-sidebar",
  "atlas-copper-sidebar",
  "atlas-narrow-index",
  "atlas-ink-sidebar",
  "atlas-sand-sidebar",
  "atlas-plum-sidebar",
  "atlas-floating-profile",
  "atlas-right-outline",
  "atlas-teal-sidebar",
  "atlas-right-cards",
  "atlas-ribbon-profile",
  "atlas-twin-ledger",
  "atlas-twin-cards",
  "atlas-newspaper",
  "atlas-crossbar",
  "atlas-split-panel",
  "atlas-offset-masthead",
  "atlas-capsule-head",
  "atlas-diagonal-head",
  "atlas-arch-portrait",
  "atlas-top-bottom",
] as const;

export type AtlasTheme = typeof atlasThemes[number];
