/** User-selected prototypes adapted to the canonical editor and print DOM. */
export const museCatalog = [
  { theme: "muse-badge", name: "蓝色工牌侧栏", source: "canva-07#r52" },
  { theme: "muse-hello", name: "HELLO 粉绿色块", source: "canva-07#r53" },
  { theme: "muse-code", name: "深蓝代码风", source: "canva-07#r54" },
  { theme: "muse-vermilion", name: "橙红底超大姓名", source: "canva-07#r55" },
  { theme: "muse-notebook", name: "黄色撕纸便签 + 线圈", source: "canva-07#r56" },
  { theme: "muse-elbow", name: "蓝绿 L 形色块", source: "canva-07#r57" },
  { theme: "muse-translucent", name: "米色半透明圆角卡片", source: "canva-07#r58" },
  { theme: "muse-charcoal", name: "深色方块页眉 + 灰侧栏", source: "canva-07#r59" },
  { theme: "muse-evergreen", name: "绿色整页 + 横线分栏", source: "canva-07#r60" },
  { theme: "muse-speech", name: "红色圆角框 + 对话气泡照片", source: "canva-07#r61" },
  { theme: "muse-taupe", name: "暖灰圆形照片 + 深色页脚", source: "canva-07#r62" },
  { theme: "muse-paperframe", name: "蓝框纸纹", source: "canva-07#r63" },
  { theme: "muse-coral", name: "珊瑚粉圆角框", source: "canva-07#r64" },
  { theme: "muse-hairline", name: "细体大名 + 双线联系栏", source: "canva-06#r33" },
  { theme: "muse-greyrail", name: "灰侧栏 + 右上灰色竖条", source: "canva-06#r34" },
  { theme: "muse-watercolor", name: "水彩浅蓝 + 深青右栏", source: "canva-06#r35" },
  { theme: "muse-slash", name: "斜杠标题 + 空心圆时间轴", source: "canva-06#r36" },
  { theme: "muse-sagegrid", name: "鼠尾草底 + 双栏网格", source: "canva-06#r37" },
  { theme: "muse-mist", name: "雾青侧栏 + 圆形图标标题", source: "canva-06#r38" },
  { theme: "muse-sky", name: "蓝天弧线 + 红色标签圆角框", source: "canva-06#r39" },
  { theme: "muse-archphoto", name: "拱形照片 + 圆点评级", source: "canva-06#r40" },
  { theme: "muse-shadowtag", name: "海军蓝侧栏 + 错位投影标签", source: "canva-06#r41" },
  { theme: "muse-redbanner", name: "红色页眉 + 双栏", source: "canva-06#r42" },
  { theme: "muse-polaroid", name: "拍立得照片 + 细体衬线名", source: "canva-06#r43" },
  { theme: "muse-yellowrail", name: "深蓝页眉 + 明黄侧栏", source: "canva-06#r44" },
  { theme: "muse-tilted", name: "砖红撞色 + 倾斜卡片", source: "canva-06#r45" },
  { theme: "muse-burgundy", name: "酒红纹理 + 等宽字体", source: "canva-06#r46" },
  { theme: "muse-violet", name: "紫色渐变 + 分栏分隔线", source: "canva-06#r47" },
  { theme: "muse-noir", name: "纯黑页面 + 窄体大名", source: "canva-06#r48" },
  { theme: "muse-spiral", name: "线圈笔记本 + 拍立得", source: "canva-06#r49" },
  { theme: "muse-crossgrid", name: "窄体巨名 + 十字格线", source: "canva-06#r50" },
  { theme: "muse-halo", name: "梦幻光晕 + 右对齐经历框", source: "canva-06#r51" },
  { theme: "muse-navymast", name: "深蓝页眉 + 图标时间轴", source: "canva-05#r19" },
  { theme: "muse-formgrid", name: "浅灰格线版式", source: "canva-05#r21" },
  { theme: "muse-bluewash", name: "浅蓝页眉 + 蓝色侧栏", source: "canva-05#r23" },
  { theme: "muse-nameband", name: "灰侧栏 + 黑色姓名条", source: "canva-05#r24" },
  { theme: "muse-diagonal", name: "蓝色斜角侧栏", source: "canva-05#r26" },
  { theme: "muse-roundrail", name: "米白纸面 + 圆角侧栏", source: "canva-05#r28" },
  { theme: "muse-twintimeline", name: "粗细姓名 + 双时间轴", source: "canva-05#r31" },
  { theme: "muse-deeprail", name: "深海军蓝侧栏", source: "canva-05#r30" },
  { theme: "muse-offsetphoto", name: "青色错位照片框", source: "canva-05#r32" },
  { theme: "muse-folded", name: "灰色侧栏 + 折角标题条", source: "canva-04#1" },
  { theme: "muse-slanted", name: "灰阶斜切页眉", source: "canva-01#1" },
  { theme: "muse-contents", name: "目录索引", source: "prototype#index" },
  { theme: "muse-numerals", name: "大号数字锚点", source: "prototype#numeral" },
  { theme: "muse-bookspine", name: "竖排书脊", source: "prototype#spine" },
  { theme: "muse-chronicle", name: "年谱", source: "prototype#annals" },
  { theme: "muse-tabs", name: "侧边页签", source: "prototype#tabs" },
  { theme: "muse-blueprint", name: "建筑 · 施工图图框", source: "prototype#arch" },
  { theme: "muse-titleblock", name: "建筑 · 竖向图签", source: "prototype#arch2" },
  { theme: "muse-drawinglist", name: "建筑 · 图纸目录", source: "prototype#arch3" },
  { theme: "muse-dealbook", name: "金融 · 交易列表", source: "prototype#finance" },
  { theme: "muse-researchnote", name: "金融 · 研报首页", source: "prototype#fin3" },
  { theme: "muse-workpaper", name: "审计 · 底稿索引", source: "prototype#audit" },
  { theme: "muse-ledger", name: "审计 · 明细账", source: "prototype#audit2" },
  { theme: "muse-memorandum", name: "法律 · 备忘录", source: "prototype#law3" },
  { theme: "muse-casebrief", name: "法律 · 案例摘要", source: "prototype#law2" },
  { theme: "muse-datasheet", name: "硬件 · 规格书", source: "prototype#spec" },
  { theme: "muse-medicalpapers", name: "医学 · 学术型", source: "prototype#med2" },
  { theme: "muse-clinicalpath", name: "医学 · 职业路径", source: "prototype#med3" },
  { theme: "muse-annotations", name: "教育 · 页边批注", source: "prototype#edu2" },
  { theme: "muse-press", name: "传媒 · 新闻稿", source: "prototype#news" },
  { theme: "muse-teaching", name: "教育 · 教学·教研·育人", source: "prototype#edu3" },
  { theme: "muse-rundown", name: "传媒 · 节目串联单", source: "prototype#news3" },
  { theme: "muse-revisions", name: "硬件 · 修订记录", source: "prototype#spec3" },
  { theme: "muse-labbook", name: "实验 · 实验记录本", source: "prototype#lab" },
  { theme: "muse-element", name: "实验 · 元素卡片", source: "prototype#lab3" },
  { theme: "muse-playbill", name: "演艺 · 场刊", source: "prototype#prog3" },
  { theme: "muse-consulting", name: "咨询 · 结论先行", source: "prototype#cons" },
  { theme: "muse-triptych", name: "姓名职位等大三区", source: "canva-03#t94" },
  { theme: "muse-rededitorial", name: "暖红编辑单栏", source: "canva-03#t84" },
  { theme: "muse-halfblack", name: "黑白五五分", source: "canva-03#t116" },
  { theme: "muse-blackmast", name: "黑色页眉 + 手写体职位", source: "canva-03#t98" },
  { theme: "muse-grainrail", name: "颗粒黑侧栏 + 灰色公司条", source: "canva-03#t113" },
  { theme: "muse-signaturerail", name: "米色侧栏 + 签名装饰", source: "canva-03#t99" },
  { theme: "muse-greeting", name: "问候语姓名 + 圆角衬底", source: "canva-03#t114" },
  { theme: "muse-greyleaders", name: "灰条标题 + 方形照片", source: "canva-02#a" },
  { theme: "muse-ruled", name: "圆形头像页眉 + 底部三栏", source: "canva-02#d" },
  { theme: "muse-righttitle", name: "姓名左上 + 职位右对齐", source: "canva-02#e" },
] as const;

export type MuseTheme = typeof museCatalog[number]["theme"];
export const museThemes = museCatalog.map(({ theme }) => theme);
